### ISSUE TITLE
Code completion doesn't trigger after commit characters

### ISSUE THREAD

**Issue by kadircet** [clangd/coc-clangd#10]
In the given example below, I've typed `Preamble->Pr.` which autocompleted last part into `Preamble.`
but didn't trigger a code completion afterwards.

![Screenshot from 2020-02-20 14-23-27](https://user-images.githubusercontent.com/897555/74937595-a55dda00-53ec-11ea-9875-25a44b514637.png)

**Comment by fannheyward** [comment]
coc.nvim had added support for commitCharacters.
