### ISSUE TITLE
Changing clangd format options?

### ISSUE THREAD

**Issue by bleonars** [clangd/coc-clangd#101]
Hello, I'm not sure how to edit the clangd format options on coc-nvim :Format. Clangd defaults to LLVM format guidelines. Is there a way to modify this setting to my liking as done by clang-format?

**Comment by kadircet** [comment]
clangd will respect formatting options specified in a .clang-format file in any of the parent directory of a file. you can also use `fallback-style` flag, but it will only take affect when there's no .clang-format file at all.
