### ISSUE TITLE
Language server is not running for: objc

### ISSUE THREAD

**Issue by akahanaton** [clangd/coc-clangd#102]
Hi
I'm trying to install coc-clangd on a macOS system (Catalina version 10.15.7), but got this error while install clangd through CocComand clangd.install:
```
[coc.nvim] Downloading clangd-mac-11.0.0.zip...
[coc.nvim] Extracting clangd-mac-11.0.0.zip...
client coc stopped!
starting coc.nvim service
[coc.nvim] imselect observer exit with code 129
Press ENTER or type command to continue
```
And the Language server cannot be started:
`Language server is not running for: objc`

Could you please give some clues how to correct it, thank you very much.

**Comment by fannheyward** [comment]
Do you have `~/.config/coc/extensions/coc-clangd-data/install/11.0.0/clangd_11.0.0/bin/clangd` exist? Checkout:

```
~/.config/coc/extensions/coc-clangd-data/install/11.0.0/clangd_11.0.0/bin/clangd --version
```

> imselect observer exit with code 129

this error is not from coc-clangd, are you using `coc-imselect`?

**Comment by akahanaton** [comment]
Hi, thanks for your comments.
Yes I have clangd installed:
```
~/.config/coc/extensions/coc-clangd-data/install/11.0.0/clangd_11.0.0/bin/clangd --version
clangd version 11.0.0 (https://github.com/llvm/llvm-project 176249bd6732a8044d457092ed932768724a6f06)
```
After uninstall coc-imselect, the error disappeared,
`[coc.nvim] Downloading clangd-mac-11.0.0.zip...                                                                                          
[coc.nvim] Extracting clangd-mac-11.0.0.zip...
client coc stopped!
starting coc.nvim service`

 but clangd service still cannot be started in neovim:
`[LC] Language server is not running for: objc`

**Comment by fannheyward** [comment]
> [LC] Language server is not running for: objc

This error is came from https://github.com/autozimu/LanguageClient-neovim

**Comment by akahanaton** [comment]
Yes, It's an error from LanguageClient-neovim, I got it running now, thank you very much
