### ISSUE TITLE
Need help debugging why file is marked as not found

### ISSUE THREAD

**Issue by romgrk** [clangd/coc-clangd#103]
One included file is marked as not found. I'd like to debug why but I'm not sure how to do so. Would it be possible to provide instructions? For example to check if clangd is receiving the compile_commands.json correctly, or if there are issues with the commands file?

![Screenshot from 2020-11-07 01-02-17](https://user-images.githubusercontent.com/1423607/98433441-22250700-2095-11eb-943d-eb72400edb88.png)

![Screenshot from 2020-11-07 01-03-45](https://user-images.githubusercontent.com/1423607/98433444-251ff780-2095-11eb-9ae0-f9e6fbf9bdd3.png)

**Logs**
Please attach the clangd log from `:CocList output` if you can: Not working

**System information**
Clangd version (from the log, or `clangd --version`): `11.0.0`
clangd extension version (from `:CocInfo`): Not found
Operating system: `archlinux`

**Comment by fannheyward** [comment]
coc-clangd v0.5.0 added `clangd.trace`, you can set a file path and clangd will log to it.

I don't know whether this will help debugging.

**Comment by vtronko** [comment]
Did you manage to find a solution to it?

**Comment by romgrk** [comment]
Nop, didn't work on that project in the last weeks

**Comment by Ferdi265** [comment]
I had a similar problem today, and the `clangd.trace` option helped.

The clangd trace had an entry "Loaded compilation database from $DIR" (where $DIR was a directory someone else put an incorrect compile_commands.json into). The log helped me debug this, but this would go so much faster if the `coc-clangd` plugin were to print a "compilation database loaded from $DIR" message into the vim status line. (or at least have an option to do this)

**Comment by fannheyward** [comment]
@sam-mccall is there any way to get the `compilation database loaded from $DIR` message without trace logs?

**Comment by vtronko** [comment]
In my case it was confused because of a file with `include_next`... That had the same filename.

**Comment by unphased** [comment]
This topic was very helpful. I would also like to strongly urge surfacing the "Loaded compilation database from" message all the way into vim somehow, because that is such a common root cause for the issue. It's a bit crazy that we have to dig around in a json trace to ferret it out. 

For my headache of the day it turned out that something dropped a compilation database with contents `[]` inside project/src where my project/compile_commands.json was perfectly good, and for whatever reason clangd chose to use project/src/compile_commands.json, much to my dismay.

**Comment by unphased** [comment]
Update on what I learned today that may help others:

- `coc-json` plugin via coc.nvim can help you see what the true configuration options are when you edit coc config via `:CocConfig`. 
- The magic for the above lies in the `package.json` of the plugins. For example: `:CocList` -> choose Extensions by typing <kbd>ext</kbd><kbd>Enter</kbd>, open clangd's coc config for coc-clangd by typing <kbd>clang</kbd><kbd>Tab</kbd><kbd>c</kbd> and it will open coc-clangd's package.json's configuration section
- From here we can see that now the name of the option is `clangd.trace.file` whereas before it was `clangd.trace`.


- I also found that `clangd.trace.file` will not work if you use a `~` path so use an absolute path to avoid the headache.

**Comment by wusatosi** [comment]
> Update on what I learned today that may help others:
> 
>     * `coc-json` plugin via coc.nvim can help you see what the true configuration options are when you edit coc config via `:CocConfig`. It will issue completions and warnings if you have stale invalid configuration keys specified in your config!
> 
>     * The magic for the above lies in the `package.json` of the plugins. For example: `:CocList` -> choose Extensions by typing extEnter, open clangd's coc config for coc-clangd by typing clangTabc and it will open coc-clangd's package.json's configuration section
> 
>     * From here we can see that now the name of the option is `clangd.trace.file` whereas before it was `clangd.trace`.
> 
>     * I also found that `clangd.trace.file` will not work if you use a `~` path so use an absolute path to avoid the headache.
> 
> 
> With all of that said, some of that is much more lower level than the only real debugging command that you need!!! This is included in the README!!! I did not discover it until today!!!
> 
> ```
> :CocCommand workspace.showOutput
> ```
> 
> That one opens a little menu that lets you choose the output to look at for any active LSP so that one helped me unscrew coc-json (it did not have npm install run on it....) and also the compilation database load path is also directly accessible for clangd from it as well. So again the TL;DR is:
> # To get useful output from a specific LSP server or plugin, _keep calm and run `:CocCommand workspace.showOutput`_

Is it possible to pipe the content of workspace.showOutput to some file?

**Comment by themightyoarfish** [comment]
Does anyone have an idea what to do if the loaded compilation database is correct? I'm still getting "file not found" on some third-party lib (but not others) and am completely lost why it does not work in this project. Works in others.
