### ISSUE TITLE
Fallback flags separately for C and C++ ?

### ISSUE THREAD

**Issue by ammen99** [clangd/coc-clangd#123]
Hello,

I find myself often editing single-files (without compile-commands.json) in both C++17 and C.
This is problematic because if I pass `-std=c++17` as fallback flag in coc-settings.json, then I get an error when I open a C file (because `-std=c++17` flag is specific for C++).

Is it possible to have fallback flags for the two languages separately?

**Comment by fannheyward** [comment]
No.

**Comment by kadircet** [comment]
You can use clangd config files to conditionally modify compileflags based on filenames, see http://clangd.llvm.org/config.html#compileflags

**Comment by ammen99** [comment]
> You can use clangd config files to conditionally modify compileflags based on filenames, see http://clangd.llvm.org/config.html#compileflags

Thank you! This works.
