### ISSUE TITLE
diagnosticsRelatedInformation: false

### ISSUE THREAD

**Issue by ZigaSajovic** [clangd/coc-clangd#124]
### Scenario

```c++
int x = 2; // 1
//...
int x = 3; // 2
```

This shows error on 2, but nothing on 1.

### Feature

To my knowledge **coc** does not have support for diagnostic related information. Hence when one uses **ccls** as a language server in **coc**, one can add

```json
        "client": {
          "diagnosticsRelatedInformation": false
        }
```
which than serves the related information as warnings, which in the above case show up on 1, and the error on 2.

Is there such a possibility within the config of the coc-clang?

**Comment by fannheyward** [comment]
> To my knowledge coc does not have support for diagnostic related information

No, coc does support this, set `"diagnostic.separateRelatedInformationAsDiagnostics": true` in your coc-settings.json.

**Comment by ZigaSajovic** [comment]
@fannheyward Thank you for clearing that up for me. It works as expected, using this setting.
