### ISSUE TITLE
Can show function list ?

### ISSUE THREAD

**Issue by mano233** [clangd/coc-clangd#132]
like [tagbar](https://github.com/preservim/tagbar)
![image](https://user-images.githubusercontent.com/29190675/101059637-760a0980-35c9-11eb-9813-36d90ee4c739.png)

**Comment by Lythenas** [comment]
There is `:CocList outline`. Which is good enough to search for something but as nice looking as tagbar.

**Comment by mano233** [comment]
> There is `:CocList outline`. Which is good enough to search for something but as nice looking as tagbar.

Oh,tks!I ignored that!
I think I might be making noise. I will close
