### ISSUE TITLE
Retain buffer cursor position after clangd.switchSourceHeader command

### ISSUE THREAD

**Issue by danvd** [clangd/coc-clangd#138]
Current behaviour: Cursor is positioned at the buffer start
Desired behaviour: Cursor is positioned at the position where it was before switching

If this is  possible.

**Comment by fannheyward** [comment]
This is already supported. 

For example, you're at server.c L33, `:CocCommand clangd.switchSourceHeader` will jump to `server.h`, and `:CocCommand clangd.switchSourceHeader` again will jump back to server.c L33.

**Comment by danvd** [comment]
Maybe there are some exceptions?

My case:

![switch_header_source_clang](https://user-images.githubusercontent.com/5666218/101992642-590ebe00-3cce-11eb-8e16-06a5218a998b.gif)

**Comment by fannheyward** [comment]
Sorry for the delay, can you try with a minimal vimrc, only coc and coc-clangd?

**Comment by danvd** [comment]
I tried the following pure config with both vim and neovim, but behaviour is still the same:
```
call plug#begin()
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'} " intellisence
call plug#end()
```
List of coc extensions:
```
  * coc-prettier 1.1.12 ~/.config/coc/extensions/node_modules/coc-prettier
  * coc-pairs 1.2.21 ~/.config/coc/extensions/node_modules/coc-pairs
  * coc-highlight 1.2.5 ~/.config/coc/extensions/node_modules/coc-highlight
  * coc-fzf-preview 0.4.27 ~/.config/coc/extensions/node_modules/coc-fzf-preview
  * coc-floaterm 0.1.3 ~/.config/coc/extensions/node_modules/coc-floaterm
  * coc-explorer 0.12.1 ~/.config/coc/extensions/node_modules/coc-explorer
  + coc-json 1.3.2 ~/.config/coc/extensions/node_modules/coc-json
  + coc-cmake 0.0.3 ~/.config/coc/extensions/node_modules/coc-cmake
  + coc-clangd 0.6.0 ~/.config/coc/extensions/node_modules/coc-clangd
```
I'll reopen this if I find the root cause. 

Thank you.

**Comment by danvd** [comment]
Probably the solution lies in vim config itself:
https://github.com/vim/vim/blob/752fc692ace51459cb407ec117c147b3bbebc071/runtime/defaults.vim#L103

Adding this autocmd does the job. Looks like it's not clangd feature but vim's and that's reasonable.
Maybe need to be indicated somewhere.
