### ISSUE TITLE
Down-rank/hide identifier-based completion items

### ISSUE THREAD

**Issue by kadircet** [clangd/coc-clangd#14]
Currently identifier-based completion items are always ranked above language server-based ones. This leads to a bad experience most of the time, for example the item I am looking for is at 18th place:
![Screenshot from 2020-02-26 11-06-58](https://user-images.githubusercontent.com/897555/75334710-9d88b480-5888-11ea-8460-5ab0bf038efa.png)

**Comment by fannheyward** [comment]
PR https://github.com/neoclide/coc.nvim/pull/1559 causes this error, I've fixed with https://github.com/neoclide/coc.nvim/pull/1589.
