### ISSUE TITLE
manually global searching of a symbol without keybindings

### ISSUE THREAD

**Issue by amirrezasadeqi** [clangd/coc-clangd#150]
Hi there. i don't know actually if this is a question or feature request but i did not know where to ask about it. so if i did it a wrong place, please forgive me.

i want to know that is there any option to search a symbol by simply typing it and not with 'gr' keybinding. there are a lot of situations in reading books and docs, for example linux kernel docs, that in them it is needed to search a function or variable from somewhere of code inwhere there are no instances of that symbol usage.

in "cscope", we can simply use `:cs find global <symbol-name>` to find all of references to that symbol. So i want to know that does coc-clangd have this feature?

**Comment by sam-mccall** [comment]
Is `:CocList symbol` what you want?

**Comment by fannheyward** [comment]
Looks like you have found it, https://stackoverflow.com/a/65431179/380774 👍

**Comment by amirrezasadeqi** [comment]
hi guys. thank for your help and sorry for my cheap question. i really don't know why i did not find this option.

yes i found it but i was very busy to post my answer here. so thank you for posting it.
