### ISSUE TITLE
Code actions don't trigger reliably

### ISSUE THREAD

**Issue by sam-mccall** [clangd/coc-clangd#17]
(coc-codeaction) sends the whole line, which doesn't work with clangd - it needs finer-grained location, like vscode provides.

(coc-codeaction-selected) works properly but only in visual/select mode I think.

Ideally we'd just change coc-codeaction to send {begin=cursor, end=cursor} - servers that want to promote this to "whole line" can easily do so, and that's what vscode does.

But if maintainers aren't happy with that we can probably do something clangd-specific or add a new binding.

**Comment by fannheyward** [comment]
Hello, can you give a sample code that can reproduce this issue?

**Comment by sam-mccall** [comment]
This was mostly fixed by neoclide/coc.nvim@bf092608a14f3915c39ce1c7057e9c8342c6914c, I hadn't synced.

I believe the new implementation provides the word touching the cursor, which should be correct in most cases.

It will still give less-than-ideal behavior in some cases, e.g. `foo*bar` with the cursor on `*` will select `[foo]*bar` I believe. I think the ideal thing (and what VSCode does) is to provide the empty range `foo[]*bar`. In this case clangd will try `foo[*]bar` and `fo[o]*bar` and use the first one that gives a usable result.

**Comment by sam-mccall** [comment]
OK, reproducer (pass `-hidden-features` to clangd).

`int foo, bar, baz = foo*bar;`

- with cursor on `o` --> selects `foo` --> "Dump DeclRefExpr AST" shows "foo" :+1:
- with cursor on `*` --> selects the whole line --> no code action :-1: - should show "Dump BinaryOperator AST"
- with cursor on `b` --> selects `bar` --> "Dump DeclRefExpr AST" shows "bar" :+1:

**Comment by fannheyward** [comment]
Your second case, with cursor on `*`, `call CocActionAsync('codeAction','')` shows `Dump TranslationUnitDecl AST`, does this expected?

**Comment by sam-mccall** [comment]
(Sorry for delay)

No, it's not expected - behaviour ("Dump TranslationUnitDecl" vs no code action offered) might vary with versions of clangd, but coc is sending the whole line range here instead of the cursor location. We want to see "Dump BinaryOperator" which is the thing under the cursor.

I'm not sure how high-priority this is, really - it's pretty confusing when trying to use the "dump selection tree" action to debug clangd, but our actual refactorings probably aren't terribly sensitive to it.

**Comment by fannheyward** [comment]
> cursor on * --> selects the whole line --> no code action 👎 - should show "Dump BinaryOperator AST"

Test with latest coc.nvim, and clangd-11, code action on `*` shows `Dump BinaryOperator AST`.
