### ISSUE TITLE
signature help contains `NONE` after linewraps

### ISSUE THREAD

**Issue by kadircet** [clangd/coc-clangd#18]
maybe something on my end got messed up, even though i haven't touched my vimrc recently. i've only updated the coc-nvim, i am suspecting the nowrap change

![Screenshot from 2020-03-08 13-35-50](https://user-images.githubusercontent.com/897555/76162888-d86cd100-6141-11ea-911e-0f991624406f.png)

**Comment by fannheyward** [comment]
Yes, coc.nvim recently fix `nowrap` set. What's your `:CocInfo`?

**Comment by kadircet** [comment]
```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 19 2019 14:03:20)
node version: v10.17.0
coc.nvim version: 0.0.75
term: dumb
platform: linux

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"b.cc" 19L, 193C
coc-google: setting updatetime=400. Set it yourself to suppress this.
[coc.nvim] Update completed
```

**Comment by fannheyward** [comment]
Are you using the `master` branch of coc.nvim?

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/issues/1604

**Comment by kadircet** [comment]
yes i am using master, it also shows up in diags:
![Screenshot from 2020-03-09 10-33-12](https://user-images.githubusercontent.com/897555/76200242-900cec00-61f1-11ea-9d53-f099d83d7cf0.png)


i've updated to https://github.com/neoclide/coc.nvim/commit/9e9b0ad3a2b218413124cfbe2ffe9db028251d5a

but issue seems to persist

**Comment by kadircet** [comment]
ok nvm, I was restarting my vim from a saved session rather than with a clean state.

restarting from scratch solved the issue after pulling, sorry for the hussle!
