### ISSUE TITLE
Unable to create newline on enter

### ISSUE THREAD

**Issue by excalios** [clangd/coc-clangd#183]
Pressing enter key only created a new line once and then it does nothing. I believe this happened because of coc.formatOnType after I disabled it it worked fine. Not sure if this is a bug or intended. Would be helpful if it still works without disabling format on type

**Logs**
![image](https://user-images.githubusercontent.com/42968441/107108174-1b16bc00-6871-11eb-8971-4e08cd6cddd1.png)

**System information**
Clangd version (from the log, or `clangd --version`): 11.0.0
clangd extension version (from `:CocInfo`): 0.8.0
Operating system: Fedora Workstation 32

**Comment by fannheyward** [comment]
Related issue https://github.com/clangd/coc-clangd/issues/33, will look into this.

**Comment by fannheyward** [comment]
`coc.preferences.formatOnInsertLeave` will be removed https://github.com/neoclide/coc.nvim/issues/2767
