### ISSUE TITLE
[Feature Request] disable auto import

### ISSUE THREAD

**Issue by GopherJ** [clangd/coc-clangd#186]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

sometimes coc-clangd tries to auto import include, which is surprising as the include is maybe already there or unnecessary. I'm wondering if it's possible to deactivate this feature?

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Please attach the clangd log from `:CocList output` if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`): 11
clangd extension version (from `:CocInfo`):
Operating system: Linux MInt v20

**Comment by kadircet** [comment]
just include `--header-insertion=never` in your compile flags.

**Comment by GopherJ** [comment]
thanks!
