### ISSUE TITLE
Remove "clangd: idle" from status bar

### ISSUE THREAD

**Issue by cheshire** [clangd/coc-clangd#193]
I'm using coc-clangd to interact with clangd, which I like very much, and like many others I show the messages in clangd in an (already crowded) status bar.
Is there any reason why coc-clangd prints "clangd: idle"? Does it add any value over just an empty string (since if it was doing something, I would assume it would print it)?

Would it be possible to change this status message to an empty string, or at least provide an option to configure it?

![image](https://user-images.githubusercontent.com/348959/108415625-a2a1ea80-71e2-11eb-8052-d0c5ad64285b.png)

**Comment by fannheyward** [comment]
Similar issue https://github.com/clangd/vscode-clangd/issues/151
