### ISSUE TITLE
Adding an extra flag option

### ISSUE THREAD

**Issue by hyt589** [clangd/coc-clangd#194]
Hi, I have been using the semantic highlight functionality to gray out sections of code skipped with `#ifdef`s, and it's been working great. However, I can't seem to find a solution to deal with compiler specific logic since there is no way to pass additional flags to `clang` in the coc config. I have tried adding a `.clangd` configuration file for my project as described in the `clangd` documentation, but it has no effect. Would you consider adding a new coc configuration field for extra `clang` flags?

**Comment by kadircet** [comment]
`.clangd` file should work for the case you've described. Could you give more details about what you tried, expected and really happened? preferably with clangd logs.

**Comment by hyt589** [comment]
> `.clangd` file should work for the case you've described. Could you give more details about what you tried, expected and really happened? preferably with clangd logs.

I placed a `.clangd` file at my project root, and typed the following lines in it:
```
CompilerFlags
  Add: [-D__GNUC__, -U__clang__]
```

I have the following snippet of code in my project:
```c++
#if defined(__clang__)
     spdlog::warn("CUDA GPU mode not supported by libraries compiled using clang, recompile use gcc");
#else
         if (
#ifdef _MSC_VER
             RunTimeLinkSuccess("OrtSessionOptionsAppendExecutionProvider_CUDA")
#else
             OrtSessionOptionsAppendExecutionProvider_CUDA
#endif
         )
```
And I am expecting to see the section of code wrapped in the `#if defined(__clang__)` macro to be grayed out, but it didn't.

I have enabled verbose logging via coc config but I don't know where `clangd` saves its log file.

**Comment by kadircet** [comment]
it is `CompileFlags` not `CompilerFlags` and you should have an additional colon `:` after `CompileFlags:`. I've tested with:
.clangd:
```yaml
CompileFlags:
  Add: [-U__clang__]
```
a.cc:
```cpp
#ifdef __clang__
static_assert(false);
#else
static_assert(false);
#endif
```

and I can verify that I am seeing the warning on the `else` branch. you can check coc documentation to figure out how to get to logs, but at some point it was possible to see via `:CocInfo`. The logs would've also contained errors about unknown keys in the config too.

**Comment by hyt589** [comment]
> it is `CompileFlags` not `CompilerFlags` and you should have an additional colon `:` after `CompileFlags:`. I've tested with:
> 
> .clangd:
> 
> ```yaml
> 
> CompileFlags:
> 
>   Add: [-U__clang__]
> 
> ```
> 
> a.cc:
> 
> ```cpp
> 
> #ifdef __clang__
> 
> static_assert(false);
> 
> #else
> 
> static_assert(false);
> 
> #endif
> 
> ```
> 
> 
> 
> and I can verify that I am seeing the warning on the `else` branch. you can check coc documentation to figure out how to get to logs, but at some point it was possible to see via `:CocInfo`. The logs would've also contained errors about unknown keys in the config too.

Thanks, I got it working now.
