### ISSUE TITLE
Can I set clangd works only with standard from c++17 

### ISSUE THREAD

**Issue by stokhos** [clangd/coc-clangd#20]
Hi,

Is there a way to set clangd only work with c++ 17 standard?
best

**Comment by fannheyward** [comment]
Try set `"clangd.arguments": ["-std=c++17"]` to your coc-settings.json.

**Comment by stokhos** [comment]
How can I do this? Do I need to unninstall coc-clangd? 
below is my coc-settings.json
{
    "languageserver": {
        "clangd": {
            "command": "clangd",
            "args": ["--background-index", "-std=c++17"],
            "rootPatterns": ["compile_flags.txt", "compile_commands.json"],
            "filetypes": ["c", "cpp"]
        },
}
this works, but is there a way of not deleting coc-clangd and add "clangd.arguments": ["-std=c++17"] to your coc-settings.json at same time?

**Comment by hokein** [comment]
To clarify, the flag `-std=c++17` is not passed to the clangd binary argument, it needs to be added in the compilation command. If you use the `compile_flags.txt`, just put it there.

>  is there a way of not deleting coc-clangd and add "clangd.arguments": ["-std=c++17"] to your coc-settings.json at same time?

Yes, if you use coc-clangd, the coc-settings.json is like below (not other fields)

```
{
   "clangd.arguments": [...]
}
```

**Comment by stokhos** [comment]
It works. Thanks guys!

**Comment by basedtho** [comment]
i did as you said in the second comment in this thread and i now get
>[coc.nvim] The "clangd" server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by kadircet** [comment]
that's WAI, as indicated in Haojian's comment

> To clarify, the flag -std=c++17 is not passed to the clangd binary argument, it needs to be added in the compilation command. If you use the compile_flags.txt, just put it there.

if you pass it to clangd, command line parsing will fail and clangd will exit with a non-zero error code.

**Comment by Waqar144** [comment]
> Yes, if you use coc-clangd, the coc-settings.json is like below (not other fields)
> 
> ```
> {
>    "clangd.arguments": [...]
> }
> ```

Doing this make clangd crash very quickly. Not recommended anymore.

I can't get C++17 support, so many errors. It isn't able to find `string_view` even. Can anyone suggest something else?

**Comment by sam-mccall** [comment]
> Doing this make clangd crash very quickly

Well, are you putting clangd flags in there? `-std=c++17` is not a clangd flag, it must go in your compile_commands.json or compile_flags.txt instead.
(clangd will not *crash* in this case, but it won't start correctly either).

Incidentally, if you really want to set this globally for all projects, the next release (clangd 11) will make this possible.

**Comment by cadenhenrich** [comment]
I used the `clangd.fallbackFlags` option and it worked fine for me.
```json
{
    "clangd.fallbackFlags": [ "-std=c++17" ]
}
```

**Comment by Waqar144** [comment]
I have found the `compile_flags.txt` method to be the best. However I still have the problem where clangd thinks `.h` files are C header files so it keeps complaining

**Comment by kadircet** [comment]
you can also put `-xc++-header` into your compile_flags.txt

**Comment by Boltzmachine** [comment]
> I used the `clangd.fallbackFlags` option and it worked fine for me. This is my `coc-settings.json`:
> 
> ```json
> {
>     "clangd.fallbackFlags": [ "-std=c++17" ]
> }
> ```

However, I got errror `In included file: unknown type name 'size_t'` when I include `<iostream>` after I set this flags

**Comment by EZ4ZZW** [comment]
> I used the `clangd.fallbackFlags` option and it worked fine for me. This is my `coc-settings.json`:
> 
> ```json
> {
>     "clangd.fallbackFlags": [ "-std=c++17" ]
> }
> ```

It's works! It's take me hole day to setting this config, every solution from internet didn't work.😭

**Comment by ljhm** [comment]
> I used the `clangd.fallbackFlags` option and it worked fine for me. This is my `coc-settings.json`:
> 
> ```json
> {
>     "clangd.fallbackFlags": [ "-std=c++17" ]
> }
> ```

I'm trying C++ in VSCode with clangd. I need this:

```
    "clangd.fallbackFlags": [
        "--std=c++2a",
    ],
```

to turn off the error messages in problem pane in VSCode, e.g.:

`No member named 'exchange' in namespace 'std'`

It has to be in "clangd.fallbackFlags". If I put it in "clangd.arguments", the outline view does not work.

**Comment by fannheyward** [comment]
@MuhammadSawalhy what's your clangd version?

**Comment by MuhammadSawalhy** [comment]
> @MuhammadSawalhy what's your clangd version?

I switched to `fallbackFlags` instead of `arguments` and it works now. Thanks!

**Comment by MuhammadSawalhy** [comment]
This doesn't work with C files!
How to use `clangd.fallbackFlags` with cpp files only?

![image](https://user-images.githubusercontent.com/42011920/208765471-dbb8afc9-0b6e-4aa6-84f9-c6ff4b1d3a91.png)

**Comment by Waqar144** [comment]
Read the following link carefully, then use compile commands to solve your problems. 

https://clangd.llvm.org/installation.html

**Comment by ljhm** [comment]
// workspace settings: 
//.vscode/settings.json
    "clangd.fallbackFlags": [
        //"-std=c99",
        "-I../foo",
    ],

for C files, I comment the -std option

**Comment by MuhammadSawalhy** [comment]
> // workspace settings:

I am coding separate and independent C++ and C files in the same project. This is [my repo](github.com/MuhammadSawalhy/problem-solving) which is a solution for problems from sites like LeetCode, Hackerrank, and Codeforces.

**Comment by Leskodamus** [comment]
> > // workspace settings:
> 
> I am coding separate and independent C++ and C files in the same project. This is [my repo](github.com/MuhammadSawalhy/problem-solving) which contains solutions for problems from sites like LeetCode, Hackerrank, and Codeforces.
> 
> So I need a way to configure `-std` flag differently for C++ and C files.

@MuhammadSawalhy Have you found a solution for having the `-std` flag separately for C and C++ files?

**Comment by colourfulspring** [comment]
> "clangd.fallbackFlags": [ "-std=c++17" ]

It works! Thanks for your reply!
