### ISSUE TITLE
Add support for clangd 13

### ISSUE THREAD

**Issue by jackhub** [clangd/coc-clangd#217]
I have downloaded the latest clangd, and coc-clangd is not working as expect. The errors from clangd are here:

E[00:18:13.621] Client requested legacy semanticHighlights notification, which is no longer supported. Migrate to standard semanticTokens request

Please help.

**Comment by fannheyward** [comment]
Set `clangd.semanticHighlighting` to false to disable semantic highlight for now.

**Comment by jackhub** [comment]
> Set `clangd.semanticHighlighting` to false to disable semantic highlight for now.

I have set this in my doc-settings.json, it works very well for clangd 12.
  "clangd.semanticHighlighting": true,

Since I noticed that, clangd 12 semantic highlight has many drawback for objective-c, so I update it to version 13. 

And coc-clangd not works for that. Some protocol has changed as the error message mentioned.

**Comment by fannheyward** [comment]
Yes, clangd 12 and 13 supports different semantic highlighting protocol, coc/coc-clangd doesn't has this now, so you need to disable semanticHighlighting for now.

**Comment by jackhub** [comment]
> > Set `clangd.semanticHighlighting` to false to disable semantic highlight for now.
> 
> I have set this in my doc-settings.json, it works very well for clangd 12.
> "clangd.semanticHighlighting": true,
> 
> Since I noticed that, clangd 12 semantic highlight has many drawback for objective-c, so I update it to version 13.
> 
> And coc-clangd not works for that. Some protocol has changed as the error message mentioned.

I guess maybe those changes will fix objective-c's semantic highlight problems, so I try to update it.
https://reviews.llvm.org/D97617

**Comment by jackhub** [comment]
> Yes, clangd 12 and 13 supports different semantic highlighting protocol, coc/coc-clangd doesn't has this now, so you need to disable semanticHighlighting for now.

Thanks for replay, I still want to use coc-clangd, so I will rollback my clangd 13, waiting for you updating...

**Comment by fannheyward** [comment]
@jackhub latest coc has added semanticTokens highlighting support, upgrade your coc to latest, enable it by `let g:coc_default_semantic_highlight_groups = 1`. Check `:h CocSem` for more infos.

**Comment by fannheyward** [comment]
coc.nvim has added semantic tokens support, check `:h coc-semantic-highlights`.
