### ISSUE TITLE
Activate coc-clangd for cuda and arduino filetype

### ISSUE THREAD

**Issue by mnrce** [clangd/coc-clangd#22]
Hi,
Please add cuda (*.cu) and arduino (*.ino) file types to coc-clangd's automatic activation list.

**Comment by fannheyward** [comment]
`coc-clangd` already supports CUDA, https://github.com/clangd/coc-clangd/blob/master/src/ctx.ts#L52, does this work for you?

**Comment by mnrce** [comment]
> `coc-clangd` already supports CUDA, https://github.com/clangd/coc-clangd/blob/master/src/ctx.ts#L52, does this work for you?

`coc-clangd` doesn't work for me when I open *.cu files (no status text and no completion), it works well when I open *.cpp files.

I checked `:CocList extensions` and `coc-clangd` was enabled when I opened a *.cu file.

Maybe because it doesn't list in the `activationEvents` array? I don't know anything about coc extensions stuff. 
https://github.com/clangd/coc-clangd/blob/master/package.json#L49

**Comment by fannheyward** [comment]
Reproduced, thanks for your report.

**Comment by fannheyward** [comment]
@mnrce What's the filetype of `.ino` file in vim?

**Comment by fannheyward** [comment]
Fixed in v0.2.4, ry `:CocUpdate`.

**Comment by fannheyward** [comment]
coc-clangd has removed `arduino` support, try https://github.com/arduino/arduino-language-server, or `coc_filetype_map` for arduino.

**Comment by vishalrao009** [comment]
what about cuda, please help for .cu files as well.
