### ISSUE TITLE
Where did clangd installed when I typed `:CocCommand clangd.install` in Vim?

### ISSUE THREAD

**Issue by nyngwang** [clangd/coc-clangd#226]
I have both Vim and NeoVim, I already did this command on Vim, but in NeoVim it ask me to type the same command to install it again, is this a bug?

I'm using MacOSX Big Sur 11.2.3 (20D91)

**Comment by fannheyward** [comment]
It's located in `~/.config/coc/extensions/coc-clangd-data/`, it should be shared with vim and nvim.
