### ISSUE TITLE
Setting priority of language server completion results

### ISSUE THREAD

**Issue by tom-anders** [clangd/coc-clangd#236]
I tried `"coc.source.clangd.priority": 1234` but that doesn't seem to have an effect.

Could there maybe be a `'clangd.priority'` option?

**Comment by fannheyward** [comment]
Why do you need this priority? The language server completion items always has higher priority.

**Comment by tom-anders** [comment]
I'm using clangd and ccls at the same time. In general, I prefer the completion format of ccls (clangd often doesn't find docstrings while ccls does, e.g. for member variables), but I really like clangd's `--all-scopes-completion` which is not available with ccls. I don't really mind that I get duplicate results in completion, but currently the clangd results are always *above* the ccls results. I'd like to have ccls at the top instead, which is why I want to lower the priority of clangd.

**Comment by fannheyward** [comment]
Set `clangd.disableCompletion` to true in your coc-settings.json.

**Comment by tom-anders** [comment]
Sure, but then I don't get *any* completion from clangd. But I *do* want to also get clangd completion, just with lower priority

**Comment by fannheyward** [comment]
It's difficult to add priority by now because coc doesn't provide priority setting for language client, will look into this.

BTW, does `suggest.languageSourcePriority` works for your case?

**Comment by tom-anders** [comment]
Thanks!

No, `suggest.languageSourcePriority` sets the priority for *all* language servers, so that doesn't have any effect here.
