### ISSUE TITLE
Always showing some unnecessary errors?

### ISSUE THREAD

**Issue by sleeperzjf** [clangd/coc-clangd#238]
Like this:
![image](https://user-images.githubusercontent.com/65698607/115182983-843a6b80-a10d-11eb-9a03-d79fd9212392.png)

**Comment by fannheyward** [comment]
Can't understand, what's the unnecessary errors?

**Comment by sleeperzjf** [comment]
Because there is no error in the `cout` expression, it runs smoothly.

**Comment by fannheyward** [comment]
https://stackoverflow.com/search?q=invalid+operands+to+binary+expression+c%2B%2B

https://stackoverflow.com/q/11620437/380774
