### ISSUE TITLE
How can I install coc-clangd offline.

### ISSUE THREAD

**Issue by leafji** [clangd/coc-clangd#245]
as develop with vim-coc, I need to install coc-clangd for c/c++ develop. 
But I can not install it online, as our company's develop env is offline.
I try to copy coc-clangd to ~/.config/coc/extension/node_modules, but it seem to not work?
Is there any other ways?

**Comment by fannheyward** [comment]
Download https://www.npmjs.com/package/coc-clangd, unpack to `~/.config/coc/extension/node_modules`.

**Comment by ShaoYu2021** [comment]
> Download https://www.npmjs.com/package/coc-clangd, unpack to `~/.config/coc/extension/node_modules`.

it doesn't work

**Comment by xc42** [comment]
> 

me too, did you find a working solution afterthen

**Comment by fannheyward** [comment]
Newer version coc-clangd uses https://github.com/clangd/node-clangd that has other dependencies, so unpack coc-clangd only couldn't work.

You can install coc-clangd in a networked env, then tar `~/.config/coc/extension/node_modules/coc-clangd` and move it to your offline env.

**Comment by xc42** [comment]
> Newer version coc-clangd uses https://github.com/clangd/node-clangd that has other dependencies, so unpack coc-clangd only couldn't work.
> 
> You can install coc-clangd in a networked env, then tar `~/.config/coc/extension/node_modules/coc-clangd` and move it to your offline env.

Thank you! It finally works!
