### ISSUE TITLE
Clangd formatting issue?

### ISSUE THREAD

**Issue by stokhos** [clangd/coc-clangd#25]
Hi:
I notice that clang has formatting feature, but I don't know how to set it up. Is there any docs for this?
best regards
Peiyun Jin

**Comment by fannheyward** [comment]
clangd is using `clang-format` to do formatting, https://clangd.llvm.org/features.html#formatting , you can set `.clang-format` for style options.

**Comment by stokhos** [comment]
Hi I have installed coc-clangd,  have .clang-format file in the project folder, and set
  "coc.preferences.formatOnSaveFiletypes": ["cpp"],
  "coc.preferences.formatOnSave": true,
But neither :Format nor format on save worked.
Could you tell me how can fix this?
Best

**Comment by stokhos** [comment]
I think the problem is caused by this line  "clangd.arguments": ["-Wall", "-Werror", "-std=c++17"]  in above in my coc-settings.json. After adding this line into my coc-settings.json. The language server stops working for some reason.
```json
{
    "coc.preferences.formatOnSaveFiletypes": ["cpp"],
    "coc.preferences.formatOnSave": true,
    "clangd.arguments": ["-Wall", "-Werror", "-std=c++17"],
    "languageserver": {
        "python": {
            "command": "python",
            "args": [
                "-mpyls",
                "-vv",
                "--log-file",
                "/tmp/lsp_python.log"
            ],
            "trace.server": "verbose",
            "filetypes": [
                "python"
            ],
            "settings": {
                "pyls": {
                    "enable": true,
                    "trace": {
                        "server": "verbose"
                    },
                    "commandPath": "",
                    "configurationSources": [
                        "pycodestyle"
                    ],
                    "plugins": {
                        "jedi_completion": {
                            "enabled": true
                        },
                        "jedi_hover": {
                            "enabled": true
                        },
                        "jedi_references": {
                            "enabled": true
                        },
                        "jedi_signature_help": {
                            "enabled": true
                        },
                        "jedi_symbols": {
                            "enabled": true,
                            "all_scopes": true
                        },
                        "mccabe": {
                            "enabled": true,
                            "threshold": 15
                        },
                        "preload": {
                            "enabled": true
                        },
                        "pycodestyle": {
                            "enabled": true
                        },
                        "pydocstyle": {
                            "enabled": false,
                            "match": "(?!test_).*\\.py",
                            "matchDir": "[^\\.].*"
                        },
                        "pyflakes": {
                            "enabled": true
                        },
                        "rope_completion": {
                            "enabled": true
                        },
                        "yapf": {
                            "enabled": true
                        }
                    }
                }
            }
        }
    }
}```

**Comment by fannheyward** [comment]
Look like it's caused by server, @sam-mccall can you look into this?

**Comment by sam-mccall** [comment]
> I think the problem is caused by this line "clangd.arguments": ["-Wall", "-Werror", "-std=c++17"] in above in my coc-settings.json. After adding this line into my coc-settings.json. The language server stops working for some reason.

The reason is `clangd.arguments` is extra flags to pass to `clangd`, and those are not valid clangd arguments:
```
$ clangd -Wall -Werror -std=c++17
clangd: Unknown command line argument '-Wall'.  Try: 'clangd --help'
clangd: Did you mean '--help'?
clangd: Unknown command line argument '-Werror'.  Try: 'clangd --help'
clangd: Did you mean '--color'?
clangd: Unknown command line argument '-std=c++17'.  Try: 'clangd --help'
clangd: Did you mean '--log=c++17'?
```

If you want to set the flags for parsing your code, this is configured using compile_commands.json or compile_flags.txt: https://clangd.llvm.org/installation.html#project-setup

**Comment by stokhos** [comment]
@sam-mccall Hi Sam, Is there a way to enable clang-tidy and -j inside coc-settings.json? Or how can I enable them with vim?
best regards

**Comment by sam-mccall** [comment]
Sure: `"clangd.arguments": ["-j=3", "-clang-tidy-checks=bugprone-*"]` - those really are clangd flags.

Similar to clang-format, for finer-grained clang-tidy config you should use the standard `.clang-tidy` config file in your source tree, clangd should respect it.

**Comment by stokhos** [comment]
@sam-mccall Do I need to enable clang-tide first, "clangd.arguments": ["-j=3", "-clang-tide=true","-clang-tidy-checks=bugprone-*"]?

**Comment by sam-mccall** [comment]
What's clangd --version?

It's on by default as of clangd 9.
It may barely work in clangd 8, it was experiencing and off by default.

**Comment by stokhos** [comment]
I'm using fedora 32 beta. Clangd is version 10.

**Comment by sam-mccall** [comment]
With clangd 10 you shouldn't have to explicitly enable clang tidy.

**Comment by chmanie** [comment]
Sorry to add to this but it seems related. I am very confused about what this plugin can do. Should I be able to do formatting? Issuing a coc `:Format` command doesn't do anything for me. Would then `clang-format` be used or `clang-tidy` with the `--fix` option (or both)?
