### ISSUE TITLE
Source clangd timeout

### ISSUE THREAD

**Issue by polak-jan** [clangd/coc-clangd#26]
I am trying Coc for the first time so I am sure I am just doing something stupid, so I apologize if that is indeed the case.

To describe my enviroment. I am using CMake to create my compilation database, and because it's build in a `build` folder I copy it to the root of the project. I also have 2 subprojects in the root folder, `core` and `gui`.

Now for the actual issue, all diagnostics seem to work fine, code navigation work fine as well. But whenever autocompletetion is expected to pop up nothing happens. Instead if you don't do anything for 5 seconds an error message appears at the bottom saying `source clangd timeout after 5000ms`. I don't have any other information to provide as I couldn't find any logs emmited by the plugin.

**Comment by fannheyward** [comment]
clangd server doesn't response completion in 5s, try to increase `suggest.timeout` in coc-settings.json. It's a server issue, `coc-clangd` can do nothing about it.

**Comment by sam-mccall** [comment]
5 seconds for completion is a long time. Can you get a clangd log (`:CocList output`) and upload it here to confirm completion latency is the problem?
