### ISSUE TITLE
Incorrect indentation with clangd snippets

### ISSUE THREAD

**Issue by user84441** [clangd/coc-clangd#266]
Default
```
int main() {
  if (condition) {
  statements <-- Bad
  } else if (condition) {
  statements <-- Bad
  }
}
```
Correct indentation
```
int main() {
  if (condition) {
    statements <-- Good
  } else if (condition) {
    statements <-- Good
  }
}
```
**System information**
Debian clangd version 12.0.1
vim version: VIM - Vi IMproved 8.2 8022856
node version: v14.17.0
coc.nvim version: 0.0.80-825a54d780
coc.nvim directory: /home/user/.vim/plugged/coc.nvim
term: dumb
platform: linux

**Comment by fannheyward** [comment]
```json
{
    "filterText": "if",
    "insertText": "if (${1:expression}) {\n${0:statements}\n}",
    "insertTextFormat": 2,
    "kind": 15,
    "label": " if (expression) {statements}",
    "score": 8,
    "sortText": "3f000000if",
    "textEdit": {
        "newText": "if (${1:expression}) {\n${0:statements}\n}",
        "range": {
            "end": {
                "character": 5,
                "line": 1
            },
            "start": {
                "character": 4,
                "line": 1
            }
        }
    }
}
```

The snippet is came from clangd, with incorrect indentation. cc @sam-mccall

**Comment by user84441** [comment]
> ```json
> {
>     "filterText": "if",
>     "insertText": "if (${1:expression}) {\n${0:statements}\n}",
>     "insertTextFormat": 2,
>     "kind": 15,
>     "label": " if (expression) {statements}",
>     "score": 8,
>     "sortText": "3f000000if",
>     "textEdit": {
>         "newText": "if (${1:expression}) {\n${0:statements}\n}",
>         "range": {
>             "end": {
>                 "character": 5,
>                 "line": 1
>             },
>             "start": {
>                 "character": 4,
>                 "line": 1
>             }
>         }
>     }
> }
> ```
> 
> The snippet is came from clangd, with incorrect indentation. cc @sam-mccall

Maybe just adding everywhere \t before statements, which will be differenet with differnet settings of:
`set expandtab shiftwidth=2 tabstop=2 softtabstop=2 `
