### ISSUE TITLE
Semantic Token hightlighting not greying out conditional macros

### ISSUE THREAD

**Issue by HearseDev** [clangd/coc-clangd#296]
Issue: The new semantic token highlighting does not grey out conditional macros defined in .clang or even at the top of the file.

I am using Neovim btw

Case 1: I have my .clangd file set to ```CompileFlags:
  Add: [-U__clang__]```
![Screen Shot 2021-07-05 at 8 58 49 AM](https://user-images.githubusercontent.com/28695977/124497423-ac7e5180-dd6f-11eb-8bc9-28d4e3b48c6a.png)

Case 2: Basic If else works with 1/0 but I think this is built in vim C behavior

![Screen Shot 2021-07-05 at 8 59 45 AM](https://user-images.githubusercontent.com/28695977/124497589-e94a4880-dd6f-11eb-8c2d-2b6716058dd5.png)

Case 3: Defining macro top of the file and using a conditional macro to see if it greys out 

![Screen Shot 2021-07-05 at 9 01 23 AM](https://user-images.githubusercontent.com/28695977/124497652-03842680-dd70-11eb-961d-56db342956e4.png)

**System information**
Clangd version (from the log, or `clangd --version`): 12.0.0
clangd extension version (from `:CocInfo`): 0.11.0
Operating system: Mac OS

**Comment by fannheyward** [comment]
<img width="145" alt="截屏2022-01-22 上午10 39 44" src="https://user-images.githubusercontent.com/345274/150621785-201cc1e7-a9d2-497b-8644-15dda345af9f.png">
 
Try coc.nvim's semantic token highlighting, check `:h coc-semantic-highlights`.
