### ISSUE TITLE
Remove old semanticHighlighting protocol

### ISSUE THREAD

**Issue by fannheyward** [clangd/coc-clangd#297]
The new `semanticTokens` highlight protocol has been added in clangd 12, clangd 13 will only support the new semanticTokens protocol, and coc.nvim also has added semanticTokens support, the old `semanticHighlighting` will be removed.

- https://github.com/neoclide/coc.nvim/pull/3186

This will be happened when clangd 13 released.

**Comment by nullromo** [comment]
I used to use `vim-lsp-cxx-highlight` and set
```json
"clangd.semanticHighlighting": true,
"coc.preferences.semanticTokensHightlihgts": false
```
in my `coc-settings.json`.

I tried removing these two lines from my config file and removing the vim-lsp-cxx-highlight plugin, but my C files are back to looking bad with nothing semantic at all.

Now that semantic tokens are supported, how do I get the proper highlighting in my C files again?

**Comment by nullromo** [comment]
When using `:call CocAction('semanticHighlight')`, I get a message saying

```
Error on request (semanticHighlight): Unable to perform semantic highlights for current buffer.
```

**Comment by fannheyward** [comment]
@nullromo

1. use latest coc.nvim release
2. enable semantic tokens highlighting for C `"semanticTokens.filetypes": ["C"]` in your coc-settings.json
3. make sure you're using clangd 13

**Comment by nullromo** [comment]
Thank you, it works! I had been scouring the coc wiki but somehow I missed [the main file that explains the options](https://github.com/neoclide/coc.nvim/blob/master/data/schema.json).
