### ISSUE TITLE
add interface to disable diagnostics

### ISSUE THREAD

**Issue by cogig** [clangd/coc-clangd#30]

**Comment by fannheyward** [comment]
Set `"diagnostic.enable": false` in your coc-settings.json.

**Comment by cogig** [comment]
Thanks for your reply.My coc-setting.json snippet about diagnostic is as follow.
``` 
 "diagnostic.enable": true,
 "coc.preferences.diagnostic.displayByAle":true,
```
If setting `"diagnostic.enable": false`,the action will close diagnostics funtion for other programming languages.All i want to do is that making coc.nvim and ale.vim work together.And I'm used to using cppcheck as linter for cpp and c.

**Comment by fannheyward** [comment]
You mean `coc-clangd` to disable diagnostics only?

**Comment by cogig** [comment]
Yes,coc-python offer `python.analysis.diagnosticEnabled` to disable diagnostics only, and if coc-clangd does what coc-python do,it maybe even better.

**Comment by fannheyward** [comment]
Use `clangd.disableDiagnostics` to disable diagnostics.
