### ISSUE TITLE
Coc.nvim : Error on "runCommand": Command: clangd.install not found

### ISSUE THREAD

**Issue by Hungpro3112** [clangd/coc-clangd#307]
![image](https://user-images.githubusercontent.com/75968004/126857212-325cdd7b-a2fa-4a6a-b05b-dd29e1ebbfc8.png)
I tried to install the lastest version of clangd but it not work 
My vim version is 8.2 
![image](https://user-images.githubusercontent.com/75968004/126857248-33df8cdb-f2e7-4549-b3cf-fa27fd0872d0.png)
And i don't know to much about clangd, so someone can guide me.
Thanks for your help.

**Comment by fannheyward** [comment]
You need to open a C/C++ file with vim to activate coc-clangd first, then use `:CocCommand clangd.install`.

**Comment by Hungpro3112** [comment]
I think the instructor more detail because it help users a lot. Thanks
