### ISSUE TITLE
set environment variables when running clangd

### ISSUE THREAD

**Issue by NitroCao** [clangd/coc-clangd#308]
I'm using clangd 12 on CentOS 7. clangd 12 requires that glibc version needs to be 2.18+, so I compiled the latest version of glibc. In order to let clangd use the latest version of glibc, I need to set `LD_LIBRARY_PATH` environment variable for it. Could you please tell me how can I implement it through modifying source code of coc-clangd?

**Comment by fannheyward** [comment]
@NitroCao can you test #309 work or not?

**Comment by NitroCao** [comment]
It seems that clangd still doesn't work even if I use the latest glibc. So I compiled clangd from source code and the extension works well. Sorry to bother you.
