### ISSUE TITLE
Download clangd server from npmjs

### ISSUE THREAD

**Issue by fannheyward** [clangd/coc-clangd#31]
https://gitter.im/neoclide/coc.nvim?at=5e9f364c2fbcdb22ace0f654
https://www.npmjs.com/package/clangd-linux

@sam-mccall

**Comment by sam-mccall** [comment]
Not sure if we want to use npm after all if we can't use it to resolve dependencies. It doesn't work for vscode and IIRC the `release` branch of coc doesn't actually require npm at all, just node, so it won't necessarily work there either.

Seems more direct just to talk to github directly in that case. We don't get fancy semver versioning but I think "is it the latest release" is enough if we stick to LLVM release cadence.

**Comment by fannheyward** [comment]
closed by #43
