### ISSUE TITLE
stdio.h not found but code still run

### ISSUE THREAD

**Issue by Hungpro3112** [clangd/coc-clangd#313]
I have a message like this:
![image](https://user-images.githubusercontent.com/75968004/127432801-23e27086-ddd3-4d09-be31-586f75cff8a4.png)
but when i run it still be ok
![image](https://user-images.githubusercontent.com/75968004/127432875-6a37fb7b-ef84-4682-9325-f72e8f6b0382.png)
I don't know why this happen?
Thanks for helping !!!

**Comment by kadircet** [comment]
Can you read https://clangd.llvm.org/guides/system-headers and see if it helps?

**Comment by fannheyward** [comment]
Try add this to your coc-settings.json:

```
  "clangd.arguments": [
    "--query-driver=/usr/bin/clang++",
    "--background-index"
  ],
```

**Comment by Hungpro3112** [comment]
> Try add this to your coc-settings.json:
> 
> ```
>   "clangd.arguments": [
>     "--query-driver=/usr/bin/clang++",
>     "--background-index"
>   ],
> ```

It doesn't work to me

**Comment by fannheyward** [comment]
@Hungpro3112 you're using Windows, change `query-driver` to your path, check https://clangd.llvm.org/guides/system-headers#query-driver for more.

**Comment by Hungpro3112** [comment]
> @Hungpro3112 you're using Windows, change `query-driver` to your path, check https://clangd.llvm.org/guides/system-headers#query-driver for more.

Windows makes me hard to install something like this. Should I change to use Linux or Mac ?

**Comment by Hungpro3112** [comment]
> @Hungpro3112 you're using Windows, change `query-driver` to your path, check https://clangd.llvm.org/guides/system-headers#query-driver for more.

Here is my project 
![image](https://user-images.githubusercontent.com/75968004/127599793-ac99bab3-5738-4034-a2d7-69b0615cd45a.png)
I put it like you said but still doesn't work
![image](https://user-images.githubusercontent.com/75968004/127599811-016bb276-f6f7-40e5-ac3a-6fa1effcbd74.png)

**Comment by snprajwal** [comment]
I'm pretty sure Windows doesn't use the `~` environment variable outside of PowerShell. You need to put the complete path to your project folder like "C:\Users\You\Desktop\C_Project\Hello_World". Right-click on your folder and see `Properties` to get the full path.

**Comment by Hungpro3112** [comment]
> I'm pretty sure Windows doesn't use the `~` environment variable outside of PowerShell. You need to put the complete path to your project folder like `"C:\Users\You\Desktop\C_Project\Hello_World"`. Right-click on your folder and see `Properties` to get the full path.

Yeah it seems not have any messages anymore but it raises a new one
![image](https://user-images.githubusercontent.com/75968004/127738491-a9071766-2e2d-471a-9b33-b4cc72c0c189.png)

**Comment by fannheyward** [comment]
@Hungpro3112 do you still have any errors with clangd?

**Comment by Hungpro3112** [comment]
> @Hungpro3112 do you still have any errors with clangd?

No, it's really good

**Comment by CatDevz** [comment]
> > @Hungpro3112 do you still have any errors with clangd?
> 
> No, it's really good

Hey when you close an issue saying you fixed your problem, but not actually providing how you fixed your problem, it makes it really frustrating for people seeing the issue later on 🙂

**Comment by hungpham3112** [comment]
> Hi @CatDevz, sorry for ambiguous comment. I was just starting to learn programming back then, so I didn't realize how important it was to answer a complete question for others.
> 
> It seems that clang didn't recognize the header file `stdio.h`. To show where clang searches for header file, open terminal and run:
> 
> `clang -v -c -xc++ nul`
> 
> It will be something like this:
> 
> ```
> clang version 16.0.6
> Target: x86_64-pc-windows-msvc
> Thread model: posix
> InstalledDir: C:\Users\sofia\scoop\apps\llvm\current\bin
>  (in-process)
>  "C:\\Users\\sofia\\scoop\\apps\\llvm\\current\\bin\\clang.exe" -cc1 -triple x86_64-pc-windows-msvc19.36.32537 -emit-obj -mrelax-all -mincremental-linker-compatible -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name nul -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -v "-fcoverage-compilation-dir=C:\\Users\\sofia" -resource-dir "C:\\Users\\sofia\\scoop\\apps\\llvm\\current\\lib\\clang\\16" -internal-isystem "C:\\Users\\sofia\\scoop\\apps\\llvm\\current\\lib\\clang\\16\\include" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\include" -internal-isystem "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\atlmfc\\include" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\winrt" -internal-isystem "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\cppwinrt" -fdeprecated-macro "-fdebug-compilation-dir=C:\\Users\\sofia" -ferror-limit 19 -fmessage-length=120 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.36.32537 -std=c++14 -fdelayed-template-parsing -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -o nul.o -x c++ nul
> clang -cc1 version 16.0.6 based upon LLVM 16.0.6 default target x86_64-pc-windows-msvc
> ignoring nonexistent directory "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\atlmfc\include"
> #include "..." search starts here:
> #include <...> search starts here:
>  C:\Users\sofia\scoop\apps\llvm\current\lib\clang\16\include
>  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include
>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt
>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared
>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um
>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt
>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt
> ```
> 
> by default clang find header file in Windows Kits (SDK) with Visual Studio installer. If you don't have multiple paths like above you need [download Visual studio](https://visualstudio.microsoft.com/). After installation, you will see ![image](https://user-images.githubusercontent.com/75968004/257593724-a3f8d1c4-978c-47b4-9d08-f9d12aed33cf.png)
> 
Click to `MSVC v143... and Windows 11 SDK`, it will takes 5 minutes. After that, clang can be recognize header file.

Let me know if this solution doesn't work for you, it's been a while, now I don't work with `C` anymore so maybe that solution out-date. Thanks.

**Comment by w9666** [comment]
Absolutely nothing works.

**Comment by helix-nuked** [comment]
huh did it work
