### ISSUE TITLE
Avoid use absolute path in coc-settings.json for clangd.path

### ISSUE THREAD

**Issue by m-lima** [clangd/coc-clangd#318]
First of all, thanks for this plugin :)

I'm opening this issue because when `:CocCommand clangd.install` is run, the absolute path of **clangd** is stored in **coc-settings.json** under `clangd.path`.
This is harmless enough, but it prevents the settings file from being host agnostic. Meaning that, if the settings are to be shared among multiple machines, the settings cannot be used without parsing/adapting.

I have a feeling that this may be how coc exports settings via the `coc.nvim` package. But since none of the other LS that I have installed (rust, go, ts) seem to need an absolute path in the settings, I'm opening the issue here.
Do let me know if this absolutely does not concern **coc-clangd** and I'll close the issue immediately ;)

Would it be possible to, instead of taking `/absolute/path/to/home/.config/coc/extensions/coc-clangd-data`, parse `<HOME_VAR>/.config/coc/extensions/coc-clangd-data` or `<COC_EXTENSION_SETTINGS>/coc-clangd`?

**Comment by fannheyward** [comment]
Yes, after `clangd.install`, coc-clangd will set `clangd.path` into your coc-settings.json, with absolute path. This needs some improvement.

**Comment by sam-mccall** [comment]
If you want to reuse coc-settings.json on different machines, can you put clangd on your $PATH and set `clangd.path` to just "clangd"? (Or leave it unset)

You'll need to do this by hand, but it doesn't seem more onerous than learning a new substitution syntax.

(VSCode's answer here is to support per-machine, per-workspace, and per-user configuration files separately.  In practice this complexity is itself a source of confusion though)

**Comment by fannheyward** [comment]
`clangd.path` will be set as `~/.config/coc/extensions/coc-clangd-data/install/12.0.1/clangd_12.0.1/bin/clangd`.

**Comment by fannheyward** [comment]
Released in v0.14.0.
