### ISSUE TITLE
Does coc-clangd support go to definition?

### ISSUE THREAD

**Issue by xspeed1989** [clangd/coc-clangd#319]
Does coc-clangd support go to definition?
I didn't find document about this

**Comment by kirillbobyrev** [comment]
Yes, it does!

Take a look at coc.nvim's documentation, e.g. `:help coc-action-jumpDefinition` and [others](https://github.com/neoclide/coc.nvim/blob/170b5fd2d904c0e9a7ace394510687447809d8dd/doc/coc.txt#L2015-L2057) (references, type definition etc). From the [example configuration](https://github.com/neoclide/coc.nvim#example-vim-configuration):

```Vim
" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
```

If this doesn't work for some reason, please let me know and feel free to reopen the issue. This does not look like a bug right now but I don't have enough context to understand whether there's something you're trying and it's not working out.

**Comment by xspeed1989** [comment]
> Yes, it does!
> 
> Take a look at coc.nvim's documentation, e.g. `:help coc-action-jumpDefinition` and [others](https://github.com/neoclide/coc.nvim/blob/170b5fd2d904c0e9a7ace394510687447809d8dd/doc/coc.txt#L2015-L2057) (references, type definition etc). From the [example configuration](https://github.com/neoclide/coc.nvim#example-vim-configuration):
> 
> ```viml
> " GoTo code navigation.
> nmap <silent> gd <Plug>(coc-definition)
> nmap <silent> gy <Plug>(coc-type-definition)
> nmap <silent> gi <Plug>(coc-implementation)
> nmap <silent> gr <Plug>(coc-references)
> ```
> 
> If this doesn't work for some reason, please let me know and feel free to reopen the issue. This does not look like a bug right now but I don't have enough context to understand whether there's something you're trying and it's not working out.

Thanks
