### ISSUE TITLE
`<avr/io.h>`  not found even though `avr-libc` is installed

### ISSUE THREAD

**Issue by K4LCIFER** [clangd/coc-clangd#324]
![image](https://user-images.githubusercontent.com/7829231/128802379-35764749-77f1-46dc-8747-b2c4ac997178.png)
 
As seen above, coc-clangd cannot find `<avr/io.h>`. It appears to not be searching in `/usr/avr/include` for `avr/io.h`.

**Logs**
```
I[20:07:39.124] clangd version 12.0.1
I[20:07:39.124] PID: 51480
I[20:07:39.124] Working directory: <hidden path>
I[20:07:39.124] argv[0]: /usr/bin/clangd
I[20:07:39.124] Starting LSP over stdin/stdout
I[20:07:39.124] <-- initialize(0)
I[20:07:39.125] --> reply:initialize(0) 0 ms
I[20:07:39.133] <-- initialized
I[20:07:39.133] <-- textDocument/didOpen
I[20:07:39.134] Failed to find compilation database for <hidden file path>
I[20:07:39.134] ASTWorker building file <hidden file path> version 1 with command clangd fallback
[<hidden path>]
/usr/bin/clang <hidden filepath> -fsyntax-only -resource-dir=/usr/lib/clang/12.0.1
I[20:07:39.136] --> textDocument/clangd.fileStatus
I[20:07:39.146] --> textDocument/publishDiagnostics
I[20:07:39.146] --> textDocument/clangd.fileStatus
I[20:07:41.133] <-- textDocument/semanticTokens/full(1)
I[20:07:41.133] --> reply:textDocument/semanticTokens/full(1) 0 ms
I[20:07:41.133] --> textDocument/clangd.fileStatus
```

**System information**
Clangd version (from the log, or `clangd --version`): 12.0.1
clangd extension version (from `:CocInfo`): Couldn't find it
Operating system: Arch Linux

**Comment by kadircet** [comment]
can you try using a `compile_flags.txt` with `--target=avr` in it?

e.g. place compile_flags.txt right next to the source file you are editing with the contents mentioned above.

Normally you should use a proper compilation database generated by your build system, which will allow clangd to figure out where to look for includes. See https://clangd.llvm.org/installation#project-setup.
