### ISSUE TITLE
warnings are slow to respond

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [clangd/coc-clangd#325]
Highlighted warnings in the code are slow to respond when the warning is fixed.
When a warning is detected, the code updates with a yellow underline. Good.
When that warning is fixed, only the statusbar (I use `vim-airline`) updates to show the number of warnings, however the highlighting still remains.
The highlighting only updates when Vim is reloaded.

**Screenshots**

_Warning Detected_:
![image](https://user-images.githubusercontent.com/79387351/129028299-7d4ecc08-d8bf-471b-beac-0a3863c1bbec.png)

_Warning Fixed_:
![image](https://user-images.githubusercontent.com/79387351/129028429-1d5ab88b-febb-4750-900e-fa5e0e67c0c6.png)

**Logs**
Please attach the clangd log from `:CocCommand workspace.showOutput` if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

![image](https://user-images.githubusercontent.com/79387351/129029130-1faf12cb-77dc-45d0-a9fb-eb4e8084f1d9.png)
_Side Note: I do **not** use_ `clang` _as my main compiler!_

**System information**
Clangd version (from the log, or `clangd --version`): `clangd version 10.0.0-4ubuntu1`
clangd extension version (from `:CocInfo`):  `0.0.80-fe35d5fe2b`
Operating system: Ubuntu-20.04 WSL

**Comment by fannheyward** [comment]
Can't reproduce with clangd 12, the warnings will disappear after saved.

**Comment by sam-mccall** [comment]
They should disappear the next time clangd generates diagnostics, which can be slow depending on the code.

(BTW putting non-preprocessor code above your includes, as in your example, will make everything slow. Filed https://github.com/clangd/clangd/issues/838 to warn on this)
