### ISSUE TITLE
Line content gets deleted after quitting Insert mode

### ISSUE THREAD

**Issue by gthomop** [clangd/coc-clangd#33]
- The problem:

Line content gets deleted but not the line itself.

- Circumstances:

Whenever quitting Insert mode and the cursor happens to be on a line which has content, as if there is a mapping doing something like this:
`imap <Esc> <S-v>s<Esc>`
Obviously, there is no such mapping.
This happens on .c, .h and .hpp files (not on .cpp), only when coc-clangd is installed and on all lines except the first of the file.

- Configuration files:

### coc-settings.json 

> {
>   "coc.preferences.formatOnInsertLeave": true,
>   "coc.preferences.formatOnType": true,
>   "coc.preferences.formatOnSaveFiletypes": [
>     "json",
>     "go",
>     "c",
>     "py",
>     "cpp",
>     "java"
>   ],
>   "suggest.completionItemKindLabels": {
>     "keyword": "\uf1de",
>     "variable": "\ue79b",
>     "value": "\uf89f",
>     "operator": "\u03a8",
>     "function": "\u0192",
>     "reference": "\ufa46",
>     "constant": "\uf8fe",
>     "method": "\uf09a",
>     "struct": "\ufb44",
>     "class": "\uf0e8",
>     "interface": "\uf417",
>     "text": "\ue612",
>     "enum": "\uf435",
>     "enumMember": "\uf02b",
>     "module": "\uf40d",
>     "color": "\ue22b",
>     "property": "\ue624",
>     "field": "\uf9be",
>     "unit": "\uf475",
>     "event": "\ufacd",
>     "file": "\uf723",
>     "folder": "\uf114",
>     "snippet": "\ue60b",
>     "typeParameter": "\uf728",
>     "default": "\uf29c"
>   },
>   "diagnostic.errorSign": "✘",
>   "diagnostic.warningSign": "",
>   "diagnostic.infoSign": "",
>   "codeLens.enable": true,
>   "coc.preferences.currentFunctionSymbolAutoUpdate": true,
>   "git.enableGutters": true,
>   "git.realtimeGutters": true
> }

### init.vim (just the coc settings)

> set nobackup
> set nowritebackup
> set cmdheight=2
> set updatetime=300
> set shortmess+=c
> set signcolumn=yes
> 
> command! -nargs=0 Prettier :CocCommand prettier.formatFile
> 
> inoremap <silent><expr> <TAB>
>     \   pumvisible() ? coc#_select_confirm() :
>     \   coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
>     \   <SID>check_back_space() ? "\<TAB>" :
>     \   coc#refresh()
> inoremap <expr><S-TAB> pumvisible() ? "\<C-n>" : "\<C-h>"
> 
> function! s:check_back_space() abort
>     let col = col('.') - 1
>     return !col || getline('.')[col - 1] =~# '\s'
> endfunction
> 
> let g:coc_snippet_next = '<TAB>'
> 
> inoremap <silent><expr> <C-space> coc#refresh()
> 
> nmap <silent> [g <Plug>(coc-diagnostic-prev)
> nmap <silent> ]g <Plug>(coc-diagnostic-next)
> 
> nmap <silent> gd <Plug>(coc-definition)
> nmap <silent> gy <Plug>(coc-type-definition)
> nmap <silent> gi <Plug>(coc-implementation)
> nmap <silent> gr <Plug>(coc-references)
> 
> nnoremap <silent> K :call <SID>show_documentation()<CR>
> 
> 
> function! s:show_documentation()
>     if (index(['vim', 'help'], &filetype) >= 0)
>         execute 'h '.expand('<cword>')
>     else
>         call CocAction('doHover')
>     endif
> endfunction
> 
> autocmd CursorHold * silent call CocActionAsync('highlight')
> 
> nmap <leader>rn <Plug>(coc-rename)
> 
> xmap <leader>f <Plug>(coc-format-selected)
> nmap <leader>f <Plug>(coc-format-selected)
> 
> nmap <leader>ca <Plug>(coc-codeaction)
> nmap <leader>cf <Plug>(coc-fix-current)
> 
> xmap if <Plug>(coc-funcobj-i)
> xmap af <Plug>(coc-funcobj-a)
> omap if <plug>(coc-funcobj-i)
> omap af <Plug>(coc-funcobj-a)
> 
> nmap <silent> <TAB> <Plug>(coc-range-select)
> xmap <silent> <TAB> <Plug>(coc-range-select)
> 
> command! -nargs=0 Format :call CocAction('format')
> command! -nargs=? Fold :call CocAction('fold', <f-args>)
> command! -nargs=0 OR :call CocAction('runCommand', 'editor.action.organizeImport')

- Maybe useful info:

OS: Void Linux, nvim v0.4.3, node v13.2.0

**Comment by fannheyward** [comment]
What's the output `:verbose imap <Esc>`? Can't reproduce, maybe caused by other vim plugin.

**Comment by gthomop** [comment]
There is no mapping to the Esc key. The problem, as I wrote on the OP, only happens on files that make coc-clangd kick in, except for .cpp ones. It does not happen on other file types. So, I am pretty sure it is a coc-clangd bug.

**Comment by gthomop** [comment]
I tried every possible combination of settings and I managed to stop this behavior by removing the first line of my coc-settings.json:
`"coc.preferences.formatOnInsertLeave": true`

From the coc.nvim documentation, this setting does the following:
> "Trigger format on type when insert leave by send \n to the server."

Maybe this has to do with clang specifically?

**Comment by fannheyward** [comment]
Reproduced.

**Comment by sam-mccall** [comment]
Minimal: 

coc-settings.json (I needed all of these)
```
  "coc.preferences.formatOnInsertLeave": true,
  "coc.preferences.formatOnType": true,
  "coc.preferences.formatOnTypeFiletypes": ["cpp"],
```

Create file containing `int;`, open it.
Type `ox<esc>` 
The new line containing x will be erased

Relevant messages:
- `textDocument/didChange`, insert "x" at line 1 char 0
- `textDocument/onTypeFormatting`, character is "\n"at line 1 char 1 (after 'x')
- formatting response: delete from line 1 char 0 to line 1 char 1

Where's the bug: unclear.

`onTypeFormatting` is underspecified, clangd expects the client to do what vscode does: edit the document first (including any client-side autoformatting) and then send the onTypeFormatting to the server.
Here, coc is sending a character of "\n" but not editing the document to include one, which doesn't seem to be a well-defined use of the protocol. In fact, formatOnType really does claim it needs to be triggered by a character that was typed, so binding exit-insert-mode to it is always going to be a stretch.
Clangd assumes that the previous "\n" is the one that was inserted, and anything between it and the point is automatic indentation. It formats the *previous* line.
We could hack around this by trying to detect the coc behavior on the server side, or make coc send something a bit less ambiguous, and teach clangd to do the right thing. What if we make "ch" the empty string?

**Comment by fannheyward** [comment]
@sam-mccall can you test the master branch? Just a quick fix to hack the ch to empty.

**Comment by fannheyward** [comment]
Here is an issue about onTypeFormatting: https://github.com/neoclide/coc.nvim/issues/1363#issuecomment-569599676

**Comment by sam-mccall** [comment]
@fannheyward Better with that patch indeed, it doesn't destroy text :-)

And it does *some* formatting, not sure if it's ever going to be great as we don't know how well-formed the code is after exiting insert mode. Depends on editing flow I guess.

That will stop "regular" format-on-type from working though: if you press enter while in insert mode it'd be nice if format-on-type activated (though I can't get that to work in coc today...)

**Comment by fannheyward** [comment]
Yes, this will stop format-on-type feature. I've revert this patch from master, and create a PR to trace it. https://github.com/clangd/coc-clangd/pull/37 (I should do in this way from the beginning...)

**Comment by sam-mccall** [comment]
> Yes, this will stop format-on-type feature

It actually *doesn't* stop format-on-type from working, clangd will reformat immediatly around the cursor if ch is sent as ''.
It's specifically ch='\n' that causes problems, because it tries to do line continuations and reindenting and stuff.
