### ISSUE TITLE
"switchSourceHeader" but instead open the other file in a split/vsplit

### ISSUE THREAD

**Issue by whisperity** [clangd/coc-clangd#331]
A usual development workflow is having the header and the source file side-by-side (vsplit). Consider jumping to a definition first, and that brings you to the implementation. Now you want to change the interface a little, which needs modifying a header file. It would be nice if there was a command (or an option to the command) which doesn't change the current window to the other buffer, but opens them in a split or vsplit.

**Comment by fannheyward** [comment]
You can set `coc.preferences.jumpCommand` in your coc-settings.json to change the jump behavior, default is `edit`, valid options: `"edit", "split", "vsplit", "tabe", "drop", "tab drop"`.

**Comment by whisperity** [comment]
That is true, but that changes the behaviour for **every** jump, not letting me assign different keybinds to this and that.

(via http://github.com/neoclide/coc.nvim/issues/318#issuecomment-451409604)
> To change all location jump behavior, set `"coc.preferences.jumpCommand": "drop"`
> 
> For definition only, use `:call CocAction('jumpDefinition', 'drop')`

However, `switchSourceHeader` is a command, not an action. Is an action version available?

**Comment by fannheyward** [comment]
Try `:CocUpdate` to coc-clangd v0.14.0, now you can `:CocCommand clangd.switchSourceHeader vsplit`, by default will use `edit` if no open command provided.

**Comment by whisperity** [comment]
Thank you very much!
