### ISSUE TITLE
How could I use any variables or directives like `pwd` to indicate current directory?

### ISSUE THREAD

**Issue by fannheyward** [clangd/coc-clangd#343]
> How could I use any variables or directives like `pwd` to indicate current directory?

I also want to know if there is any way to do this. Tried to use `$(pwd)` and `${PWD}` but without success. I work on a project where the build folder stays in a totally different path outside the project folder but the path is based on the project folder name. In VSCode I can just use the variables provided like `${workspaceFolder}` or `${workspaceFolderBasename}`.

_Originally posted by @AlefCS in https://github.com/clangd/coc-clangd/issues/77#issuecomment-903929957_

**Comment by fannheyward** [comment]
Try coc-clangd 0.15.0, now you can use some vars like `${cwd}` `${workspaceFolder}` in VSCode.

**Comment by juxuny** [comment]
${cwd} also worked on my vim editor.

**Comment by ObiWahn** [comment]
@juxuny please take a look here: https://github.com/clangd/coc-clangd/pull/456
