### ISSUE TITLE
[question] does this plugin have auto formatting and indent size to 2?

### ISSUE THREAD

**Issue by alexzanderr** [clangd/coc-clangd#345]
im in a cpp file:
```cpp
#include <cmath>
#include <iostream>

using namespace std;

int main() {

  cout << "hello wordl!" << endl;

  return 0;
}
```

i have installed `coc-prettier` and i have set `"prettier.tabWidth": 4` in `coc-settings.json` and i still get indent size of 2 spaces when i save the cpp file.

it seems that the plugin(coc-clangd) automatically indents the c and cpp file.

any ideas? thanks.

**Comment by kirillbobyrev** [comment]
Yes, clangd uses [ClangFormat engine](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) for formatting and defaults to LLVM Style Guide (2 spaces indent width). You could adjust the style you're most comfortable with through `.clang-format` configuration file. The easiest way to make the style "global" is to put `.clang-format` into your home directory or anywhere in the common root of your projects (see https://github.com/clangd/coc-clangd/issues/39 for reference).

If you have other questions or this doesn't solve your issue, please let me know and feel free to reopen the bug.

**Comment by alexzanderr** [comment]
i guess my `.clang-format` file should look this if i want indent size to be 4:
```
IndentWidth: 4
```
right?

**Comment by kirillbobyrev** [comment]
> i guess my `.clang-format` file should look this if i want indent size to be 4:
> 
> ```
> IndentWidth: 4
> ```
> 
> right?

Yes, correct, that would be enough!

**Comment by alexzanderr** [comment]
wow. it works. thank you so much!

**Comment by alexzanderr** [comment]
another question:
is there a way to put this in `~/.config/clang-blabla` ?
because i want the home dir to be more cleaner.

**Comment by kirillbobyrev** [comment]
Unfortunately, I don't think this is possible. See https://github.com/clangd/coc-clangd/issues/39 for more details on the config "globalness".

**Comment by alexzanderr** [comment]
i dont see a solution in that thread. thanks anyway.

**Comment by markdestouches** [comment]
Clangd ignores the .clang-format file and resorts to default style for some reason. The exact same file work just fine when called via nvim-lsp

**Comment by alexzanderr** [comment]
wut?

**Comment by alexzanderr** [comment]
we were talking about global config file for clang formatter
