### ISSUE TITLE
coc-clangd on vim sometimes will complete with extra character

### ISSUE THREAD

**Issue by hanleylee** [clangd/coc-clangd#351]
I encountered a very strange issue: 

https://user-images.githubusercontent.com/35610874/132379017-22b6e8ce-2488-47ff-bc8e-f53a7a8d6126.mp4

As what I did in the above video, when I use `<C-y>` to complete a item, it will give me some extra character, the extra character is depend on what I input at that time. I can confirm I don't have any keymap for `<C-y>`(actually, I encountered this issue when I use <cr> to complete item, for reproduce I deliberately used the <c-y> key).

![telegram-cloud-photo-size-5-6179478575187602853-m](https://user-images.githubusercontent.com/35610874/132379416-dc9b4b8f-b5e8-4134-8554-0adb921b79e8.jpg)

There are some strange points for this issue:

1. This issue only exists in coc with vim. If I use neovim, this issue will disappear, I have tried many times
2. This problem is not always present, it will occur once in a dozen or twenty times

**System information**
Clangd version (from the log, or `clangd --version`): 12.0.1
clangd extension version (from `:CocInfo`): 0.15.0
Operating system: macos

**Comment by fannheyward** [comment]
What's your coc.nvim version? Check from `:CocInfo`, this issue should be fixed already https://github.com/neoclide/coc.nvim/issues/3290.

**Comment by hanleylee** [comment]
I confirm my `coc.nvim` is latest:

```vim
undefined## versions

vim version: VIM - Vi IMproved 8.2 8022681
node version: v16.8.0
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /Users/hanley/.vim/plugged/coc.nvim
term: dumb
platform: darwin
```

And this issue is only in vim, after I switch to nvim, this issue will disappear, I have tried many days. It's weird.

**Comment by fannheyward** [comment]
@hanleylee do you use the master or release branch? If you're using the master branch, increase the timeout to 200 and try again https://github.com/neoclide/coc.nvim/blob/03c9add7cd867a013102dcb45fb4e75304d227d7/src/model/document.ts#L78

**Comment by hanleylee** [comment]
No help, I changed the number from 20 to 500, it still complete extra character sometimes(Not always, it's about a 5% chance)

**Comment by Andoku** [comment]
Can confirm, I have the same issue but it happens more often, maybe in 50-70% chance. Sometimes characters are in the beginning and sometimes at the end.

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/issues/3290

**Comment by fannheyward** [comment]
@hanleylee I've checked this issue with vim 8.2.3600, can't reproduce anymore, can you give it a test?

**Comment by hanleylee** [comment]
@fannheyward Confirmed! By the way, which commit fix this?

**Comment by fannheyward** [comment]
@hanleylee have no idea about the commit, maybe something in vim has been improved.
