### ISSUE TITLE
How stop clangd from start for .ino files

### ISSUE THREAD

**Issue by listout** [clangd/coc-clangd#352]
Is is possible to not start clangd for certain filetypes in vim?

For example when I open and .ion (arduino sketch) file in vim, clangd start reports `clang: fe_expected_compiler_job`. Is there anyway I can stop this behavior.

**Comment by kirillbobyrev** [comment]
Hey! I don't know if there is a way to directly disable a particular plugin through coc.nvim mechanism but there certainly is one for vim-plug if you're installing the plugin with that or autocmds. Please check https://github.com/neoclide/coc.nvim/issues/349 for more info.

**Comment by listout** [comment]
Thank you.

I managed to solve the issue my manually configuring clangd through `coc-config.json` and removing coc-clangd. That way I could configure clangd for custom filetypes.

**Comment by fannheyward** [comment]
coc-clangd has removed arduino support.
