### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by leo94666** [clangd/coc-clangd#359]
![image](https://user-images.githubusercontent.com/71742460/133102194-f951dd56-a106-47f2-90dd-3f4afdd738d2.png)
os:macos 11.4
llvm:12.01
press gd can go to header file,but this tips?why?

**Comment by fannheyward** [comment]
Check https://github.com/clangd/vscode-clangd/issues/230#issuecomment-917865593 and https://github.com/clangd/vscode-clangd/issues/100
