### ISSUE TITLE
Server language.clangd failed to start: Launching server "languageserver.clangd" using command clnagd

### ISSUE THREAD

**Issue by thesimpleboy** [clangd/coc-clangd#365]
When I created a C / C++ file，coc will display following error
![image](https://user-images.githubusercontent.com/83897793/136416616-a55356bd-3c4f-4960-9274-bca3e92f85ff.png)

coc-settings.json
```
"clangd": {
                        "command": "clangd",
                        "rootPatterns": ["compile_flags.txt", "compile_commands.json"],
                        "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp"]
                  }
```

Is my coc-settings.json configuration incorrect,please help me,thanks :)

**Comment by fannheyward** [comment]
You're not using `coc-clangd`, but setup clangd in your coc-settings.json. You can remove clangd configurations in your coc-settings.json, install coc-clangd.

**Comment by thesimpleboy** [comment]
![image](https://user-images.githubusercontent.com/83897793/136497934-549fb0fe-eac4-458e-8270-c908939b6223.png)

Well,before commit this issue,I have installed coc-clangd and it has enabled,but coc still display the same error,what can I do?

**Comment by thesimpleboy** [comment]
I removed all of about clangd in coc-settings.json,error message was disappear. But now,the question is coc not provide me syntax completion
![image](https://user-images.githubusercontent.com/83897793/136501116-f28c0deb-2b37-4899-962d-f62428319b8e.png)
