### ISSUE TITLE
Triage: behavior of coc/clangd/ale seems to depend on state of the file

### ISSUE THREAD

**Issue by reportaman** [clangd/coc-clangd#376]
Am not 100% sure where this is stemming from, but think coc-clangd is the place to begin the triage for a bunch of reasons.

I have a very simple C++ "helloworld" program that I wrote to play with code actions "Fixits" feature of clangd, and have come across issues that I had not previously seen with other language servers/linters I have used. What I observe is that the behavior of diagnostics being displayed or not, and code action being available or not depends on the state of the file in vim.

In the attached screencast, I have opened 3 similar files. We will explore working with an error "missing header file for printf" in all 3.

1. helloworld1.cpp
2. helloworld2.cpp
3. helloworld3.cpp

The difference between 1, and {2,3} is that 1 already had the error of interest before it was opened in neovim; {2,3} did not have that error before they were opened in neovim. 

1. For helloworld1.cpp, code actions do not work at all. Doing ``\qf`` returns an error from coc.
2. For helloworld2.cpp, we first introduce the error by deleting the header include that declares printf, the error is correctly displayed. Technically at this point, the contents of the file are same as helloworld1.cpp Though this time hitting ``\qf`` does run the code action correctly, and inserts the missing header file to correct the error.
3. For helloworld2.cpp, I follow the same steps as helloworld2.cpp, except that I first save the file ``:w<CR>`` after inserting the error and before correcting it. This time pressing ``\qf`` does correct the error (by inserting the missing header file), but it starts showing an incorrect that printf (a standard library function) is being defined defined on that line. Saving the file clears the warning.

Am using ALE to display the diagnostics, but I have not seen such problems with ALE and other coc-nvim language servers, which makes me suspicious that the source of problem could be coc-clangd.

Here's the code:

```cpp
#include <cstdio>
#include <stdlib.h>

int main(void){
    printf("Hello world!%ld", sizeof(size_t));
}
```

https://user-images.githubusercontent.com/71736629/143669673-24926463-2e8a-4ec5-92a0-e2e0e1e26e8c.mp4

**Comment by sam-mccall** [comment]
The issue with (1) is not that code actions don't work, it's that no code action is available. Until you've had some file open that (transitively) includes cstdio, we don't have it in the index. This is basically working as intended, but https://github.com/clangd/clangd/issues/403 covers implicitly indexing the standard library.

(2) is working correctly.

(3) I don't have an explanation for, in particular how we are seeing the "implicitly declaring" warning instead of not found or no warnings. This must be a clangd bug, clangd verbose logs would be useful (I can't reproduce it)
