### ISSUE TITLE
coc.vim install coc-clangd Installed extension coc-clangd@0.17.0 failed

### ISSUE THREAD

**Issue by hudengjunai** [clangd/coc-clangd#389]
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Please attach the clangd log from `:CocCommand workspace.showOutput` if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`):
clangd extension version (from `:CocInfo`):
Operating system: centos7
latest ,install 'coc-clangd' failed,

node version: v16.13.1

**Comment by fannheyward** [comment]
Post `CocInfo` when you install failed.
