### ISSUE TITLE
clangd does not identify basic headers (iostream , vector , etc.)

### ISSUE THREAD

**Issue by TheLastGuard** [clangd/coc-clangd#390]
Hi, I really don't know if it's a bug or a simple misconfiguration of mine, but coc-clangd doesn't identify headers like <iostream>, <vector>, etc.

**Comment by abdoulayegk** [comment]
Can you share a screenshot of your code(header) or your config file to make it easier?

**Comment by sam-mccall** [comment]
https://clangd.llvm.org/troubleshooting#cant-find-standard-library-headers-map-stdioh-etc

Sorry, there's no actionable info in this report.
