### ISSUE TITLE
Header extension .h interpreted as C

### ISSUE THREAD

**Issue by VukanJ** [clangd/coc-clangd#40]
Is there a way to configure coc-clangd (or clangd) so that the header extension ".h" is interpreted as a C++ header by default, or is the language (C/C++) determined exclusively by the file extension in clangd and coc-clangd? I was at least unable to find a way to force the language to C++, but it could be that I am missing something. According to the [CppCoreGuidelines](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#S-source): **"The specific names .h and .cpp are not required (just recommended as a default) and other names are in widespread use. Examples are .hh, .C, and .cxx. Use such names equivalently"**. Since people often cannot choose the header extensions for the projects they are working on, I am guessing that there must be a way to configure this on the language server side?

**Comment by VukanJ** [comment]
I figured it out by myself: Setting the language flag `-xc++` explicitly sets the language for all files. Sorry for the spam

**Comment by zhengweidi** [comment]
Hey, can you tell me how you solved this problem?

**Comment by zhengweidi** [comment]
Hey, can you tell me how you solved this problem?

**Comment by VukanJ** [comment]
Sure, you just need to run :CocConfig and write the following line to your coc-settings.json file:
```
{
    "clangd.fallbackFlags" : ["-xc++ -othercompilerflagsofyourchoice"]
}
```
For my use cases, setting fallbackFlags  to the compiler flags I always use is sufficient. But adding the `-xc++` flag to `compile_flags.txt` works as well

**Comment by zhengweidi** [comment]
> Sure, you just need to run :CocConfig and write the following line to your coc-settings.json file:
> 
> ```
> {
>     "clangd.fallbackFlags" : ["-xc++ -othercompilerflagsofyourchoice"]
> }
> ```
> 
> For my use cases, setting fallbackFlags to the compiler flags I always use is sufficient. But adding the `-xc++` flag to `compile_flags.txt` works as well

thx!

**Comment by proc-moe** [comment]
Thanks, clangd interpreted .h as C++ in my machine, I solved it by adding -xc to compile_commands.json like this
``` json
[
  {
    "arguments": [
      "-xc"
      ]
    }
]
```

**Comment by Mikael-Pereira** [comment]
I know this is old but it helped a lot.
For those searching latter it might be useful to add, you can add this same argument in a .clangd file at the root of the source files (if you have project specific configs there) or in the global config.yaml file.

`CompileFlags:
   Add: [
     -xc++,
     -std=c++20,
  ]`

For me it was complaining about -std=c++20:

> clang: Invalid argument '-std=c++20' not allowed with 'C' [drv_argument_not_allowed_with]

For me he was treating all .h files as C headers.

**Comment by chvolow24** [comment]
I had a similar problem. clangd thought the.h files in my C project were "Objective-C++" (didn't even know that was a thing). I would contend that that _is_ a bug, maybe to do with how libc is set up on MacOS. I finally fixed it after finding this thread and adding `-xc` to CompileFlags.

**Comment by chvolow24** [comment]
> > I had a similar problem. clangd thought the.h files in my C project were "Objective-C++" (didn't even know that was a thing). I would contend that that _is_ a bug, maybe to do with how libc is set up on MacOS. I finally fixed it after finding this thread and adding `-xc` to CompileFlags.
> 
> can you please elaborate your solution?

Sure thing. In the root directory of your project, create a file called `.clangd` if it does not already exist. Add any compiler flags you want clangd to emulate inside the square brackets, separated by commas:

```
CompileFlags:
    Add: [-xc]
```
(-xc is the one that fixed the issue for me)

Hope this works for you too!
