### ISSUE TITLE
Main cannot be declared as global variable

### ISSUE THREAD

**Issue by GodShin** [clangd/coc-clangd#401]
When writing a simple "hello world"-file
coc-clangd throws errors: Main cannot be declared as global variable [clang: main_global_variable]
and at return: Expected expression [clang: expected_expression

What does that mean?

My code is

`#include<iostream>`

`int main{`

`return0;}`

I also can't compile so does that have to do with my clang installation not working?

Thanks, Alex

**Comment by kirillbobyrev** [comment]
The [main function](https://en.cppreference.com/w/cpp/language/main_function) declaration has incorrect syntax: you're missing parentheses (and also the space between `return` and `0`); ->

```c++
include <iostream>
int main() {
  return 0;
}
```

Clangd simply warns about incorrect code, this isn't a bug or a problem in either Clang or Clangd (diagnostics are correct).

**Comment by GodShin** [comment]
Thanks, stupid of me!
