### ISSUE TITLE
How to enable semantic highlights for coc-clangd?

### ISSUE THREAD

**Issue by ethan-enhe** [clangd/coc-clangd#410]
I've set "semanticTokens.filetypes" to ["*"] in my configurations for coc.nvim, but symbols are not hightlighted.

**Comment by fannheyward** [comment]
1. make sure you're using clangd 13
2. put your cursor on the symbols, fire `:CocCommand semanticTokens.inspect` you will get the semantic token info. You can also use `:CocCommand semanticTokens.checkCurrent` to get full tokens.
