### ISSUE TITLE
*.S file suggest support

### ISSUE THREAD

**Issue by pangchol** [clangd/coc-clangd#411]
coc-clangd not support some assembly language file jump to define (this type file often exist in linux kernel source code, suce as: arch/arm/kernel/head.S), if use coc-settings.json like :

    "languageserver": {
        "clangd": {
            "command": "clangd",
            "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp", "asm"],
            "args": ["--background-index"],
            "rootPatterns": ["compile_commands.json",  ".git/", ".svn/"]
        }
    }

it will work for *.S file (vim set ), so suggest add support for assembly language file.

**Comment by sam-mccall** [comment]
Clangd doesn't support assembly files. Some preprocessor features may happen to work, but I wouldn't expect other features to, and I'd expect to see a lot of suprious errors.
