### ISSUE TITLE
Launch clangd with nice -n 19

### ISSUE THREAD

**Issue by RedBeard0531** [clangd/coc-clangd#414]
By default clangd consumes all cores which can make the editor drag after saving a widely-included header. Using a high niceness helps avoid this. For now, I have a trival wrapper script around clangd that just runs `exec nice -n 19 clangd "$@"` and point `"clangd.path"` to the script instead of the real clangd. But that feels like a bit of a hack and I'd hesitate to recommend that to everyone. Ideally coc-clangd would just do the right thing by default. Possibly by offering a `"clangd.niceness"` option that defaults to 19

**Comment by fannheyward** [comment]
cc @sam-mccall what's your thoughts on this?

**Comment by kadircet** [comment]
you can pass `-j=X` to clangd to limit the amount of parallelism. clangd already performs background indexing with idle thread priority (on platforms that support it), hence it shouldn't take priority over other running threads. the rest of the CPU usage should probably be temporary, it's for updating currently open files (and diagnostics you might have on them).

**Comment by RedBeard0531** [comment]
In vim i usually have several hundred "open" files at any time, even though only 2 or 3 are currently visible. I'd rather not have clangd stealing CPU from my editor at any time, especially to update files that I'm not currently typing in. But I don't actually want to limit parallelism since I still want it to use any spare cycles on otherwise idle cores.

Ideally coc could tell clangd which files are visible vs just "open" but I don't think that is a part of the LSP spec. OTOH using nice solves this issue nicely without needing any cooperation from clangd. Is there any downside?
