### ISSUE TITLE
Doesn't find clangd anymore after update from 0.21.0 to 0.21.1

### ISSUE THREAD

**Issue by sdroege** [clangd/coc-clangd#430]
After updating coc-clangd from 0.21.0 to 0.21.1, clangd is not found anymore. A downgrade to 0.21.0 makes it work again.

This is on Linux, with clangd in `PATH`:

```console
$ which clangd
/usr/bin/clangd
```

**System information**
Clangd version:
```
Debian clangd version 13.0.1-3+b1
Features: linux+grpc
Platform: x86_64-pc-linux-gnu
```
clangd extension version (from `:CocInfo`): 0.21.1

**Comment by fannheyward** [comment]
Try v0.21.2.

**Comment by derekschrock** [comment]
Nope still can't find it.

**Comment by fannheyward** [comment]
@derekschrock do you have `clangd.path` set in your coc-settings.json? In my tests, you don't need to set `clangd.path`, coc-clangd will find clangd from bundled, PATH.

**Comment by fannheyward** [comment]
Try v0.21.3

**Comment by sdroege** [comment]
Thanks, this works now.
