### ISSUE TITLE
[NeoVim coc-clangd] Too many errors omitted + linter isnt working right (read for more)

### ISSUE THREAD

**Issue by itsrxmmy** [clangd/coc-clangd#439]
This only just started happening recently. But whenever I start editing my C++ programs, the linter says 

```
Too many errors emitted, stopping now
[clang: fatal_too_many_errors]
```
at the top. Strangely enough, ALL of the errors produced are produced in lines that have ```std::string```

the message reads as follows:

```
Use of undeclared identifier 'std'
[clang: undeclared_var_use]
```

It is insanely annoying that all the strings I work with produce an error for clangd. Of course its fine when I actually run it, but damn is this annoying and in order for me to tell if a new error appeared, I have to either scroll through my code or go to all my std::string usages and subtract them from the count.

I tried reinstalling coc-clangd via ```:CocInstall coc-clangd``` and it didnt fix it. So then I tried reinstalling LLVM which reinstalled clangd too and that didnt work.

**Comment by itsrxmmy** [comment]
Also i forgot to add,

```#include <iostream>``` produces an error too.

```
'iostream' file not found
[clang: pp_file_not_found]
```

**Comment by fannheyward** [comment]
Do you have a `compile_commands.json` for your project?

The errors were came from clangd, coc-clangd just display them.
