### ISSUE TITLE
How would I go by disabling coc-clangd's auto-include header feature?

### ISSUE THREAD

**Issue by slightly-seasoned** [clangd/coc-clangd#440]
I'm working with C and SDL2 and unnecessary headers are stacking up in my files since `coc-clangd` doesn't realise that the header files its including are already included in the `SDL.h` header file.

Is there a way I could disable this feature?

**Comment by fannheyward** [comment]
It's clangd's work for this.

**Comment by SeanCodingThings** [comment]
Why was this closed, i need to know this. How do i disable auto-include feature???
