### ISSUE TITLE
wrong root path: clang pp_file_not_found

### ISSUE THREAD

**Issue by Freed-Wu** [clangd/coc-clangd#441]
Please describe the problem.

Take x264 as an example:

```
$ git clone --depth=1 https://github.com/mirror/x264
$ cd x264
$ vi +28 encoder/encoder.c
```

![Screenshot from 2022-04-23 22-34-17](https://user-images.githubusercontent.com/32936898/164910463-7f9243e9-eb56-448e-8647-5b93ba78df08.png)

coc.nvim use `.git` as coc.preferences.rootPatterns, so the root path is `.`. However, clangd use `encoder`, so `common/*.h` cannot be found, but `encoder/*.h` can be found.

For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Please attach the clangd log from `:CocCommand workspace.showOutput` if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
```

I[22:27:44.700] clangd version 13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
I[22:27:44.700] Features: linux+grpc
I[22:27:44.700] PID: 1618219
I[22:27:44.700] Working directory: /home/wzy/Desktop/x264
I[22:27:44.700] argv[0]: ../../.config/coc/extensions/coc-clangd-data/install/13.0.0/clangd_13.0.0/bin/clangd
I[22:27:44.700] Starting LSP over stdin/stdout
I[22:27:44.701] <-- initialize(0)
I[22:27:44.701] --> reply:initialize(0) 0 ms
I[22:27:44.730] <-- initialized
I[22:27:44.732] <-- textDocument/didOpen
I[22:27:44.733] Failed to find compilation database for /home/wzy/Desktop/x264/encoder/encoder.c
I[22:27:44.733] ASTWorker building file /home/wzy/Desktop/x264/encoder/encoder.c version 1 with command clangd fallback
[/home/wzy/Desktop/x264/encoder]
/usr/bin/clang -resource-dir=/home/wzy/.config/coc/extensions/coc-clangd-data/install/13.0.0/clangd_13.0.0/lib/clang/13.0.0 -- /home/wzy/Desktop/x264/encoder/encoder.c
I[22:27:44.734] --> textDocument/clangd.fileStatus
I[22:27:44.742] --> workspace/semanticTokens/refresh(0)
I[22:27:44.742] --> textDocument/clangd.fileStatus
I[22:27:44.767] <-- reply(0)
I[22:27:44.775] --> textDocument/publishDiagnostics
I[22:27:44.776] --> textDocument/clangd.fileStatus
```

**System information**
Clangd version (from the log, or `clangd --version`): 13.0.1
clangd extension version (from `:CocInfo`): 0.21.3
Operating system: linux 5.17.1-arch1-1

**Comment by fannheyward** [comment]
Can't reproduce.

1. `git clone --depth=1 https://github.com/mirror/x264`
2. `cd x264`
3. `bear -- make` to generate compile_commands.json
4. `nvim +28 encoder/encoder.c`, no errors.

**Comment by Freed-Wu** [comment]
```vim
" $ uname -r
" 5.17.7-arch1-1
" $ has nvim
" ✔ nvim 0.7.0
" $ has python
" ✔ python 3.10.4
" $ cat test.vim
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
let g:coc_config_home = '.'
" $ cat coc-settings.json
" $ vi -u test.vim +28 encoder/encoder.c
```

![Screenshot from 2022-05-22 22-13-29](https://user-images.githubusercontent.com/32936898/169699469-0b357182-802f-4c65-84b4-c27374b6b344.png)

**Comment by fannheyward** [comment]
How do you set `compile_commands.json` for the project?
