### ISSUE TITLE
Wrong hint in <iostream> header file

### ISSUE THREAD

**Issue by zhengweidi** [clangd/coc-clangd#46]
![image](https://user-images.githubusercontent.com/31889177/81181652-58e36d00-8fdf-11ea-9cb1-3580f69b20d2.png)

**Comment by Happy-zyy** [comment]
遇到了相同的问题，请问楼主怎么解决的？

**Comment by zhengweidi** [comment]
实际上这是因为项目中有某个文件（ffmpeg的time.h）与系统的time.h同名了，你可以把这个文件改名或者从项目include路径中排除掉

**Comment by Happy-zyy** [comment]
多谢楼主，我目前遇到的是这个情况，就是单独写的一个文件，但是找不到c++的标准库，请问你有遇到过吗？
<img width="357" alt="图片" src="https://user-images.githubusercontent.com/25721721/81523250-e4625280-937f-11ea-9cf6-8aea4318a99b.png">

**Comment by zhengweidi** [comment]
> 多谢楼主，我目前遇到的是这个情况，就是单独写的一个文件，但是找不到c++的标准库，请问你有遇到过吗？
> <img alt="图片" width="357" src="https://user-images.githubusercontent.com/25721721/81523250-e4625280-937f-11ea-9cf6-8aea4318a99b.png">

:CocConfig 打开配置文件，加上
```
{
        "clangd.arguments":["-xc++"]
}
```

**Comment by Happy-zyy** [comment]
感谢楼主的回复，我按照您说明的更改之后：
<img width="386" alt="图片" src="https://user-images.githubusercontent.com/25721721/81524437-c4349280-9383-11ea-9562-bd45f0701551.png">
coc直接失去了LSP功能，C/C++都失去个功能
<img width="354" alt="图片" src="https://user-images.githubusercontent.com/25721721/81524396-9b140200-9383-11ea-871e-239117c39d15.png">
请问您知道是怎么回事吗，我刚接触这个，请您多指点，非常感谢~！

**Comment by zhengweidi** [comment]
你可以看看这个issue
https://github.com/clangd/coc-clangd/issues/40#issuecomment-624628250
