### ISSUE TITLE
Disabling Unknown Word Warning

### ISSUE THREAD

**Issue by pgosar** [clangd/coc-clangd#466]
To my knowledge, it is currently not possible to suppress warnings related to unknown words. It would be great if this was a configuration option.

**Comment by fannheyward** [comment]
What do you mean `unknown words warning`? Can you post an example?

**Comment by pgosar** [comment]
For example: 
![image](https://user-images.githubusercontent.com/55164602/172763001-05ee3de8-4add-43ba-b16c-c8bc9351bad8.png)
You can see it near the bottom by my status bar. Each yellow bar on the sign column is a line where those warnings are present.

**Comment by fannheyward** [comment]
I don't think this warning was came from coc-clangd, try minimal vimrc.
