### ISSUE TITLE
clangd: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by jsholmes** [clangd/coc-clangd#47]
I tired :CocCommand clangd.install to get clangd rather than using apt-get.  It installed, but could not run because of the following error:

```
## Output channel: clangd

[Error  - 2:27:16 PM] /mnt/harmonix_vol2/soporifix_vol3/user/home/john/.config/coc/extensions/coc-clangd-data/install/10rc3/clangd_10rc3/bin/clangd exited with code: 1
/mnt/harmonix_vol2/soporifix_vol3/user/home/john/.config/coc/extensions/coc-clangd-data/install/10rc3/clangd_10rc3/bin/clangd: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /mnt/harmonix_vol2/    soporifix_vol3/user/home/john/.config/coc/extensions/coc-clangd-data/install/10rc3/clangd_10rc3/bin/clangd)
```

**Comment by sam-mccall** [comment]
Yikes, sorry. The binaries *used* to be quite portable (requiring only glibc 2.18) when I set up these builds, but of course it regressed because I didn't have a test.

I'm working on fixing this, and will disable the auto-install feature meanwhile.

**Comment by sam-mccall** [comment]
@fannheyward FYI i've republished the old 0.3.4 manually as 0.4.1 to roll back this feature for now - the binary releases aren't as portable as they're supposed to be.

**Comment by sam-mccall** [comment]
@jsholmes I think I've fixed the builds and would like to turn the auto download feature back on. Would you be able to confirm the Linux binary here works for you?

https://github.com/clangd/clangd/releases/tag/10.0.0

(It's still built on a newer machine, but with magic to tell it to link to the older versions of the glibc symbols)

**Comment by jsholmes** [comment]
Yep, that ran for me:
```
❯ /usr/scratch/tmp/clangd_10.0.0/bin/clangd
clangd is a language server that provides IDE-like features to editors.

It should be used via an editor plugin rather than invoked directly. For more information, see:
	https://clang.llvm.org/extra/clangd/
```

**Comment by sam-mccall** [comment]
Thank you! I've marked it as stable and will turn on the autodownloader again (maybe after the weekend though!)

And thanks for the report!

**Comment by fannheyward** [comment]
0.4.2 has released.
