### ISSUE TITLE
Is it possible to disable function parameter hinting popup?

### ISSUE THREAD

**Issue by millaker** [clangd/coc-clangd#474]
I've been trying to disable the parameter hinting popup or toggling it. I've tried to add 
`"clangd.inlayHints.enable" : false` in coc-settings and add 
```
InlayHints:
  Enabled: No
```
in .config/clangd/config.yaml, neither worked. I've also tried using clangd.inlayHints.toggle command by typing `:CocCommand clangd.inlayHints.toggle` but responded `Command: not found`. This may be a dumb question, I'm new to vim and really don't know how to use the configuration json file.

Edit:
After some tries, I found that adding `"clangd.disableCompletion": true` in coc-settings.json did work as expected. However, `"clangd.inlayHints.enable": false` still doesn't work.
![image](https://user-images.githubusercontent.com/63972968/176751012-cf8df5cb-2787-482c-8b29-427f6bc8c17a.png)

Edit:
`inlayHints.enable` probably works, it is not the popup window.

**Comment by millaker** [comment]
So I read some source code and found:
```
get inlayHints() {
    const virtualText = workspace.isNvim && workspace.nvim.hasFunction('nvim_buf_set_virtual_text');
    return {
      enable: virtualText && (this.cfg.get('inlayHints.enable') as boolean),
      sep: this.cfg.get('inlayHints.sep', '‣'),
    };
```
I know nothing about javascript and typescript, but I assume this feature is only for neovim?  Is it possible for Vim user to disable this?

**Comment by millaker** [comment]
After digging into the source code and some research, I came up with this solution:
```
function! ClosePopUp()
    if coc#float#has_float()
        call coc#float#close_all()
        return ''
    endif
    return ''
endfunction

inoremap <silent><expr> <C-d> ClosePopUp()
```
Don't know if there are other ways to disable function hinting popups, but this solves my problem in the short run.

**Comment by fannheyward** [comment]
It's `signatureHelp`, you can set `"signature.target": "echo"` to move the signature to messages.

**Comment by millaker** [comment]
> It's `signatureHelp`, you can set `"signature.target": "echo"` to move the signature to messages.

Thank you so much!
