### ISSUE TITLE
doxygen documentation is shown in hover window with escaped punctiation

### ISSUE THREAD

**Issue by jsholmes** [clangd/coc-clangd#48]
I don't know if this is a coc issue or a coc-clangd issue, but when I get hover information about a symbol, the documentation is shown with escaped punctuation making it quite hard to read.  See screenshot.

```
## versions

vim version: NVIM v0.5.0-dev
node version: v14.1.0
coc.nvim version: 0.0.78-57637bb44c
term: screen-256color
platform: linux

## Output channel: clangd log

I[14:23:11.272] clangd version 9.0.1-8+hrt1hrt9.1
```

<img width="617" alt="Screen Shot 2020-05-07 at 2 28 43 PM" src="https://user-images.githubusercontent.com/288824/81331420-92fc4f80-906f-11ea-958b-c6d90c574b0d.png">

**Comment by sam-mccall** [comment]
Its fundamentally a coc issue: it requests the markdown version of the hover card, but then doesn't unescape the text per markdown rules.

That said, much escaping is optional and latest clangd should be doing much less (though there are common cases where it can't be avoided)

**Comment by jsholmes** [comment]
Yeah... I'm working to get my codebase building with clang-10.  I'm on clang-8 right now, so maybe that's causing a lot of the excess markdown.

**Comment by jsholmes** [comment]
well, clangd-10 still has ample excess markdown.

**Comment by sam-mccall** [comment]
I'm sure that's true, but do you have an example?

**Comment by jsholmes** [comment]
Same example, but for clangd-10 rather than 9.

<img width="617" alt="Screen Shot 2020-05-08 at 11 44 12 AM" src="https://user-images.githubusercontent.com/288824/81422667-48d3a680-9121-11ea-913d-6f77fa9d1aac.png">

**Comment by sam-mccall** [comment]
My mistake, the escaping changes didn't make the clangd-10 release :-(

It looks better at trunk, thought there are still a few backslashes we can't easily drop:

![image](https://user-images.githubusercontent.com/548993/81442504-fec7e080-9173-11ea-93b6-ce38e515bce9.png)

(The t%2 typo is bothering me, sorry about that...)

**Comment by sam-mccall** [comment]
The wrapping is still terrible, we do detect the hard breaks after the colons but this is a good example of where assuming short lines imply hard breaks would be a big win.

**Comment by jsholmes** [comment]
Why did you guys stop preserving the line breaks?  Seems like that could at least be an option.

**Comment by talk2drys** [comment]
is there a work around for this?. 
![clangd_hover_format_error](https://user-images.githubusercontent.com/32944188/82737913-55472a00-9cf1-11ea-840a-4ff0872bc3b7.png)

**Comment by kadircet** [comment]
we've improved escaping recently. you can build clangd at head, or use a binary from our [weekly releases](https://github.com/clangd/clangd/releases)

**Comment by talk2drys** [comment]
thanks @kadircet  I tested it with the latest snapshot, and saw improvement. attached is the updated screenshot.
I also added screenshot on the snapshot and copied the hover text to an online markdown it displayed correctly there

![updated_clangd_version](https://user-images.githubusercontent.com/32944188/82744040-8bf06500-9d30-11ea-9197-7de93a344681.png)

![updated_view](https://user-images.githubusercontent.com/32944188/82744041-8f83ec00-9d30-11ea-813f-c43ba98dcb62.png)

![online_view](https://user-images.githubusercontent.com/32944188/82744044-9874bd80-9d30-11ea-8b3e-ae37e39d1b02.png)

**Comment by Lythenas** [comment]
It looks like they don't want to fix this in coc (neoclide/coc.nvim#2308). I often use markdown in my doc comments so this is really annoying.

Is it possible to tell clangd to do no escaping at all?

**Comment by flw-cn** [comment]
@jsholmes You can try `Plug “flw-cn/vim-markdown”` which is a fork for `plasticboy/vim-markdown` and it automatically hides the backslash. see PR plasticboy/vim-markdown#515 to see exactly what it does.

**Comment by fannheyward** [comment]
coc.nvim has rework document highlights, https://github.com/neoclide/coc.nvim/issues/2497, please upgrade your coc.nvim and try again.

**Comment by GopherJ** [comment]
I also have some documentation issue: ![image](https://user-images.githubusercontent.com/33961674/104594380-5d354f00-5671-11eb-89a0-ab8a77b48553.png)

**Comment by fannheyward** [comment]
Latest clangd has improved a lot, close for now.
