### ISSUE TITLE
'iostream' file not found

### ISSUE THREAD

**Issue by KyVinhMai** [clangd/coc-clangd#483]
Hello, I'm a bit new to vim so I apologize for my newbieness and my limited understanding of anything.

![image](https://user-images.githubusercontent.com/68800355/179523874-eb0c8794-40ee-44fd-80eb-f358e820e33e.png)

I have an issue where the 'iostream' file is not found.

I essentially followed this  YouTube video here: https://www.youtube.com/watch?v=7-dfpQ5sexk&t=627s . Where he shows how to install the clangd extension (7:26).

I already have MingW installed.

The clangd --version command doesn't show on the command line so I don't know if that should be concerning.

Operating System: Windows 10

**Comment by fannheyward** [comment]
You need to setup `compile_commands.json` for your project, checkout https://clangd.llvm.org/installation#project-setup
