### ISSUE TITLE
Include errors

### ISSUE THREAD

**Issue by ItzZisker** [clangd/coc-clangd#491]
Recently i've been migrating to work with cli text-editors for fun, but i got problems into using it.
the problem is including libraries from linux modules api.

## Result from CocInfo

versions:

```vim version: NVIM v0.7.2
node version: v18.7.0
coc.nvim version: 0.0.82-5fce9a51 2022-08-17 07:04:08 +0800
coc.nvim directory: /home/kalix/.local/share/nvim/site/pack/coc/start/coc.nvim
term: xterm-256color
platform: linux
```

Log of coc.nvim:

```2022-08-18T19:21:12.561 INFO (pid:98204) [plugin] - coc.nvim initialized with node: v18.7.0 after 135ms
2022-08-18T19:21:12.579 INFO (pid:98204) [services] - registered service "clangd"
2022-08-18T19:21:12.580 INFO (pid:98204) [services] - clangd state change: stopped => starting
2022-08-18T19:21:12.585 INFO (pid:98204) [language-client-index] - Language server "clangd" started with 98216
2022-08-18T19:21:12.616 INFO (pid:98204) [services] - clangd state change: starting => running
2022-08-18T19:21:12.625 INFO (pid:98204) [services] - service clangd started
2022-08-18T19:24:24.350 INFO (pid:98204) [attach] - receive notification: showInfo []
```

## Describe the bug

I added all include paths into both compile_flags.txt & compile_commands.json

compile_flags.txt:

```
-I/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/include -I/usr/lib/modules/5.18.16-arch1-1/build/arch/x86/include -I/usr/lib/modules/5.18.16-arch1-1/build/arch/x86/include/generated -I/usr/lib/modules/5.18.16-arch1-1/build/include -I/usr/lib/modules/5.18.16-arch1-1/build/arch/x86/include/uapi -I/usr/lib/modules/5.18.16-arch1-1/build/arch/x86/include/generated/uapi -I/usr/lib/modules/5.18.16-arch1-1/build/include/uapi -I/usr/lib/modules/5.18.16-arch1-1/build/include/generated/uapi
```

compile_commands.json:

```
[
{
  "directory": "/home/kalix/rickroll-driver",
  "command": "clang -std=c11 -I/home/kalix/rickroll-driver -I/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/include -I/usr/lib/modules/5.18.16-arch1-1/build/arch/x86/include -I/usr/lib/modules/5.18.16-arch1-1/build/arch/x86/include/generated -I/usr/lib/modules/5.18.16-arch1-1/build/include -I/usr/lib/modules/5.18.16-arch1-1/build/arch/x86/include/uapi -I/usr/lib/modules/5.18.16-arch1-1/build/arch/x86/include/generated/uapi -I/usr/lib/modules/5.18.16-arch1-1/build/include/uapi -I/usr/lib/modules/5.18.16-arch1-1/build/include/generated/uapi -I/usr/lib/modules/5.18.16-arch1-1/build/include/linux",
  "file": "/home/kalix/rickroll-driver/rickroll.c"
}
]
```

i checked all of the directories, and they were okay, i can switch into, i can list the files inside, and it works on vscode already.

## Reproduce the bug

.wimrc:
```
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()
```

## Screenshots:
![image](https://user-images.githubusercontent.com/68909399/185432960-816f919a-6345-4c32-8a32-5d34ec170b82.png)
inside init.h:
![image](https://user-images.githubusercontent.com/68909399/185433055-103e132a-8a4b-44ca-b364-670be3b3b791.png)
compiler.h:
![image](https://user-images.githubusercontent.com/68909399/185433108-ed6550e6-afdd-4f36-8bee-9658846b4b8d.png)
compiler_types.h (no errors):
![image](https://user-images.githubusercontent.com/68909399/185433216-d59dfa94-10b0-46de-92a4-b85276c38ef1.png)

and whenever i try to include them inside the header itself (readonly) (just by testing to see if the completion works or not):
![image](https://user-images.githubusercontent.com/68909399/185433634-758b9c55-2e8d-4d8d-9c93-a52cb60ab3d2.png)
it just doesn't find it, while the init.h and compiler.h and compiler_types.h, together are exactly in the same directory.

last words:
the code compiles, and works with no problems (CMake), it also can be edited by vscode with no errors, the code style is in C11 standard.

**Comment by fannheyward** [comment]
Where is your `compile_commands.json` located? It should be in your project's root.

**Comment by ItzZisker** [comment]
> Where is your `compile_commands.json` located? It should be in your project's root, or use `clangd.compilationDatabasePath` to specifies the directory containing the compilation database.

it is in root path, yes i did, it has problem reading these two header files init.h and module.h, other ones are okay, the completion also works (for example netfilter header enums, etc), but it spits errors whenever i include init.h & module.h, if i delete compile_commands.json, they all would be red.

**Comment by fannheyward** [comment]
> these two header files init.h and module.h, other ones are okay

it's clangd's issue, cc @sam-mccall

**Comment by ItzZisker** [comment]
> it's clangd's issue, cc

wait i think i found the issue, it says "C99", while i need C11 standard, i tried adding it to `compile_commands.json` as i mentioned, but it doesn't work, it still thinks its C99, any solution?

**Comment by fannheyward** [comment]
Add it to `clangd.arguments` and try again.

**Comment by ItzZisker** [comment]
> Add it to `clangd.arguments` and try again.

![image](https://user-images.githubusercontent.com/68909399/187065899-9ef77be6-4b86-4796-92b0-4f2b62400322.png)
![image](https://user-images.githubusercontent.com/68909399/187065890-aca7227b-b1ae-470c-8b15-164cd9165632.png)
i tried this, but it doesn't even start at all

**Comment by fannheyward** [comment]
Try `clangd.fallbackFlags`, https://github.com/clangd/coc-clangd/issues/20#issuecomment-670946925

**Comment by ItzZisker** [comment]
> Try `clangd.fallbackFlags`, [#20 (comment)](https://github.com/clangd/coc-clangd/issues/20#issuecomment-670946925)

i tried adding `"clangd.fallbackFlags": [ "-std=c11" ]` to `coc-settings.json` but still got back to the first place
![image](https://user-images.githubusercontent.com/68909399/188279577-44a01539-e4e9-4677-a140-ec14da7a8cf6.png)
i wonder does this even support c at all?

**Comment by elijahdanko** [comment]
Looks like newer versions of clangd drop supporting --std option

**Comment by fannheyward** [comment]
You need to set `-std` in compile_commands.json, https://github.com/clangd/coc-clangd/issues/516

**Comment by sam-mccall** [comment]
To clarify clangd's behavior here:

-std is a clang flag (not a clangd flag) and can be set in any of the usual places, {compile_commands.json, compiler_flags.txt} (only ONE of these will be used), .clangd (can add flags), fallback flags (ONLY if there's no compile_commands or compile_flags)

https://clangd.llvm.org/design/compile-commands

If you're editing a header file, it's likely compile_commands.json didn't have flags for it. (Most build systems don't compile headers separately).
Clangd will try to guess based on a similarly-named file that does have flags. Details are in the logs.

If you want to see which C version is being used, type `__STDC_VERSION__` and hover over it. Checking to see whether there are any diagnostics is not a reliable method, as you could have several problems.
