### ISSUE TITLE
Signature help doesn't clear underline

### ISSUE THREAD

**Issue by kadircet** [clangd/coc-clangd#5]
Current parameter is underlined in the signature help window, but as you keep moving onto other parameters the old ones keep the underline.

![Screenshot from 2020-02-19 14-37-53](https://user-images.githubusercontent.com/897555/74839365-76306580-5325-11ea-94ee-871b94717f19.png)

**Comment by sam-mccall** [comment]
Found it: https://github.com/neoclide/coc.nvim/pull/1567
