### ISSUE TITLE
Setting index chache to alternative folder

### ISSUE THREAD

**Issue by GiuseppeCesarano** [clangd/coc-clangd#50]
When i run nvim with coc-clangd a `./clangd/` is created in my project. It looks like to contain some index cache,  i want those files in another location for example `/tmp/clangd` is that possible?

**Comment by fannheyward** [comment]
I don't find any `./clangd/` folder created. Does clangd will create this? cc @sam-mccall

**Comment by sam-mccall** [comment]
yes, clangd will store index files under `.clangd` your project root, next to `compile_commands.json`.
There's no option to change this currently, we're working on adding a configuration scheme that will allow this sort of thing (as it should vary per-project).

**Comment by unphased** [comment]
my clangd (version 10 on ubuntu 18.04) is not producing any `.clangd/` anywhere on my filesystem (I checked). How can I make it start to use index files? My project is too big and it is making my laptop very hot.
