### ISSUE TITLE
Add command to show type hierarchy similar to call hierarchy

### ISSUE THREAD

**Issue by RedBeard0531** [clangd/coc-clangd#502]
This is already [implemented](https://clangd.llvm.org/extensions#type-hierarchy) in clangd. And coc already has the tree viewer for things like outline and call hierarchies. Hopefully it is fairly easy to hook the two up. The [docs](https://github.com/neoclide/coc.nvim/blob/605642d6e947da0f34c0369fc785144b5ecb2cca/doc/coc.txt#L3148-L3169) mention the `window.createTreeView` function being the api provided for extensions.

This is something that I miss since moving from [ccls](https://github.com/m-pilia/vim-ccls#commands). Personally I would prefer a single tree view that had showed both subclasses and superclasses of the requested class, since often I'm interested in both. Plus then I'd only need to add and remember a single binding rather than two.

**Comment by fannheyward** [comment]
clangd's type hierarchy is implemented in off-spec protocol. LSP 3.17 has official added type hierarchy support, and coc.nvim supports this. Does clangd support official LSP type hierarchy? @sam-mccall  

- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareTypeHierarchy

**Comment by sam-mccall** [comment]
Clangd 15 does support the standard type hierarchy protocol. This release was only finalized a few days ago, looks like we don't even have binaries up yet... I'll get on that

**Comment by sam-mccall** [comment]
Binaries now at https://github.com/clangd/clangd/releases/tag/15.0.0 however not pushed to Autoupdate yet until final testing
