### ISSUE TITLE
Cannot set standard

### ISSUE THREAD

**Issue by elwolf6** [clangd/coc-clangd#516]
Can't set standard to c++2b
`"clangd.arguments": ["-std=c++2b"]` in my coc-settings.json

I get `[coc.nvim] Server clangd failed to start: Error: Pending response rejected since connection got disposed`  even with `-std=c++17` sometimes i also get `restarting server failed`

**Comment by fannheyward** [comment]
Same issue https://github.com/clangd/coc-clangd/issues/491

@sam-mccall does clangd drop support for `-std` flag?
