### ISSUE TITLE
How to avoid flahing messages in the status line?

### ISSUE THREAD

**Issue by FlanOfHarmony** [clangd/coc-clangd#524]
I'm using `coc-clangd` along with `vim-airline` and am very satisfied with it, except for the part that whenever I'm typing code (insert mode therefore) there are two messages, `clangd: file is queued` and `clangd: parsing includes` that keep flashing in the status line, something that I find extremely disrupting.

I took a look at the example [`coc-settings.json`](https://github.com/fannheyward/init.vim/blob/master/coc-settings.json) and the configuration for [`coc-clangd`](https://github.com/clangd/coc-clangd#Configurations), especially `clangd.disableProgressNotifications`, as well as the vim `coc-status` entry of the coc vim manual, but I just don't find any way to prevent this behavior. Maybe some arguments can be passed to clangd to silence these messages? Without completely disabling the other status lines features of `coc-clangd` of course.

**Comment by fannheyward** [comment]
You can't disable the status by now, will improve this.
