### ISSUE TITLE
clangd.inlayHints.enable won't work now

### ISSUE THREAD

**Issue by swang203** [clangd/coc-clangd#525]
Previously, I could turn off the in lay hints through
{
  "clangd.path": "~/.config/coc/extensions/coc-clangd-data/install/15.0.1/clangd_15.0.1/bin/clangd",
  "clangd.inlayHints.enable": false,
  "semanticTokens.enable": true,
  "suggest.noselect": true,
}

But it seems not to work anymore, and my code is full of these intrusive hints. 
What would be the new option to turn if off? 

Thanks for your attention and reply :)

**Comment by fannheyward** [comment]
Use `inlayHint.enable`, check `:h coc-inlayHint` for more.
