### ISSUE TITLE
Do I need a compile_commands.json for getting basic autocompletion?

### ISSUE THREAD

**Issue by lifeBalance** [clangd/coc-clangd#53]
Just trying to get autocompletion for C but can't make it work. So far I've taken the following steps:
* In my init.vim I have `Plug 'neoclide/coc.nvim', {'branch': 'release'}`, save file, reload and `:PlugInstall`
* Then `:CocInstall coc-clangd` and `:CocCommand clangd.install`
* Run `:chechhealth`, everything under health#coc#check is OK and green.
* Open a C source file, but can't get any completion suggestion at all. I tried restarting Neovim and nothing.
I didn't generate a `compile_commands.json`, not sure how to do that. My "project" is basically a bunch of loose files (I'm learning C) but do I really need a compile_commands.json for getting basic autocompletion?

**Comment by ivechan** [comment]
No. 
`compile_commands.json` is better but  `compile_flags.txt may `be enough in you situation.

> If all files in a project use the same build flags, you can put those flags one-per-line in **compile_flags.txt** in your source root.
> Clangd will assume the compile command is clang $FLAGS some_file.cc.
>Creating this file by hand is a reasonable place to start if your project is quite simple.

**Comment by lifeBalance** [comment]
Hey, thanks. Not sure about what flags should I use. I tried this:
```
--std=c17
```
trying to get completion in basic stuff like `scanf` or `printf` but nothing is triggered.

**Comment by lifeBalance** [comment]
Nevermind, it was a conflict with **ale**

**Comment by hakanohi** [comment]
@lifeBalance mind telling me how you solved the issue? I just installed coc-clangd and when I open vim it does not even seem to recognize basic headers. Since I'm working with a bunch of random loose files, I don't know if i should have compile_commands.json.
