### ISSUE TITLE
target_include_directories isn't working

### ISSUE THREAD

**Issue by PneumaOfficial** [clangd/coc-clangd#535]
So my project structure is as such:
```
project
           |-.vim
           |-CMakeLists.txt
           |-compile_commands.json
           |-src
                  |-main.cpp
                  |-include
                                |-Framework.h
```
While the project builds with cmake just fine, clangd is showing this error: 
![image](https://user-images.githubusercontent.com/39502544/205413354-8dfe9d1c-1a91-44f2-847c-67a20b544631.png)

My coc config is this:
```
  "languageserver": {
    "clangd": {
      "command": "clangd",
      "rootPatterns": ["compile_flags.txt", "compile_commands.json"],
      "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp"],
          "compilationDatabasePath": "/home/ubuntu/project/compile_commands.json"
    }
  }
```
I have tried just specifying `/home/ubuntu/project/` but no luck
It ONLY errors in Framework.h, inside main.cpp it includes it just fine

**Comment by fannheyward** [comment]
Do you use `coc-clangd`? Check your `:CocList extensions`. From your config, you setup clangd in coc-settings.json's `languageserver`, not coc-clangd.

If you're using coc-clangd, you don't need to set in coc-settings.json.

**Comment by PneumaOfficial** [comment]
> Do you use `coc-clangd`? Check your `:CocList extensions`. From your config, you setup clangd in coc-settings.json's `languageserver`, not coc-clangd.
> 
> If you're using coc-clangd, you don't need to set in coc-settings.json.

I don't understand, so how would I specify my compile_commands.json?

**Comment by fannheyward** [comment]
1. remove clangd section from your coc-settings.json
2. use coc-clangd `:CocInstall coc-clangd`, make sure you have coc-clangd in `:CocList extensions`
3. Set `clangd.compilationDatabasePath` in coc-settings.json

**Comment by PneumaOfficial** [comment]
> 1. remove clangd section from your coc-settings.json
> 2. use coc-clangd `:CocInstall coc-clangd`, make sure you have coc-clangd in `:CocList extensions`
> 3. Set `clangd.compilationDatabasePath` in coc-settings.json

Aren't I already doing that?

**Comment by fannheyward** [comment]
One question: do you have coc-clangd in `:CocList extensions`?

**Comment by PneumaOfficial** [comment]
> One question: do you have coc-clangd in `:CocList extensions`?

Yes

**Comment by fannheyward** [comment]
Set `"clangd.compilationDatabasePath": "/path/to/your/compile_commands.json",` in your coc-settings.json.

**Comment by PneumaOfficial** [comment]
> 

Its not working, I've tried:
```
  "languageserver": {
    "coc-clangd": {
      "command": "clangd",
      "rootPatterns": ["compile_flags.txt", "compile_commands.json"],
      "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp"],
          "clangd.compilationDatabasePath": "/home/ubuntu/project/compile_commands.json"
    }
  }
```

```
 "clangd.compilationDatabasePath": "/home/ubuntu/project/compile_commands.json"
```

and

```
{
      "clangd.compilationDatabasePath": "/home/ubuntu/project/compile_commands.json"
}
```

**Comment by fannheyward** [comment]
```
  "languageserver": {
    "coc-clangd": {
      "command": "clangd",
      "rootPatterns": ["compile_flags.txt", "compile_commands.json"],
      "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp"],
          "clangd.compilationDatabasePath": "/home/ubuntu/project/compile_commands.json"
    }
  }
```

You don't need this when you use coc-clangd.

Try `"clangd.compilationDatabaseCandidates": "/home/ubuntu/project/"`.

**Comment by PneumaOfficial** [comment]
> "clangd.compilationDatabaseCandidates": ["/home/ubuntu/project/"]

No luck

**Comment by fannheyward** [comment]
Have no idea about this, clangd needs compile_commands.json to work but it failed on your project.

**Comment by PneumaOfficial** [comment]
> 

Its whats being generated after my project successfully builds
