### ISSUE TITLE
coc-clangd not targetting compile_commands.json

### ISSUE THREAD

**Issue by PneumaOfficial** [clangd/coc-clangd#536]
My project structure is this:
```
.
├── .clangd
├── build
│   ├── CMakeCache.txt
│   ├── CMakeFiles
│   ├── Makefile
│   ├── cmake_install.cmake
│   └── compile_commands.json
└── src
    ├── CMakeLists.txt
    ├── include
    │   └── Framework.h
    ├── lua
    └── main.cpp
```

The problem is when I am editing `./src/main.cpp`, there are no errors. CMake builds properly and generates the compile_commands to `./build`.

HOWEVER, when I edit `./src/include/Framework.h`, it believes a linked library is not found, using the same include used in main.cpp.
I have already tried setting `.clangd`:
```
CompileFlags:
  CompilationDatabase: build/
```
and I have already tried: 
`"clangd.compilationDatabaseCandidates": ["/home/ubuntu/project/"]` and `"clangd.compilationDatabasePath": "/home/ubuntu/project/"` with no results.

I have already ensured the it is `coc-clangd` I am using and not `clangd`.
A previous attempt at resolving it exists here, to reference what I have already tried: https://github.com/clangd/coc-clangd/issues/535

**Comment by fannheyward** [comment]
As I said in previous issue, there's something wrong with clangd to work on your project.

coc-clangd is a client, it sends some requests, for example document hover, completions etc, to clangd. clangd published diagnostics and coc-clangd just displayed them. So I have no idea about why clangd can't work on your project.

You can try VSCode + https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd to make sure it works or not. If same issue, you need to check clangd to make it works. If it works as protect, there should be something broken on coc.nvim + coc-clangd, please provide an example project same as your project that I can debug it.

**Comment by PneumaOfficial** [comment]
> As I said in previous issue, there's something wrong with clangd to work on your project.
> 
> coc-clangd is a client, it sends some requests, for example document hover, completions etc, to clangd. clangd respond with results, published diagnostics and coc-clangd just displayed them. So I have no idea about why clangd can't work on your project.
> 
> You can try VSCode + https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd to make sure it works or not. If same issue, you need to check clangd to make it works. If it works as protect, there should be something broken on coc.nvim + coc-clangd, please provide an example project same as your project that I can debug it.

https://github.com/PneumaOfficial/coc-example
I have done such. The only thing you need to do on your end is replace the includes with something you have on your system, and update the CMakeList.txt to reflect that.

**Comment by PneumaOfficial** [comment]
> As I said in previous issue, there's something wrong with clangd to work on your project.
> 
> coc-clangd is a client, it sends some requests, for example document hover, completions etc, to clangd. clangd respond with results, published diagnostics and coc-clangd just displayed them. So I have no idea about why clangd can't work on your project.
> 
> You can try VSCode + https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd to make sure it works or not. If same issue, you need to check clangd to make it works. If it works as protect, there should be something broken on coc.nvim + coc-clangd, please provide an example project same as your project that I can debug it.

Idk if you've already tried or not, but the directories were weirded out on github, but they're fixed now
https://github.com/PneumaOfficial/coc-example

**Comment by fannheyward** [comment]
I didn't debug this yet, will work on this tonight.

> try VSCode + https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd

Does VSCode + clangd work in this case?

**Comment by PneumaOfficial** [comment]
> I didn't debug this yet, will work on this tonight.
> 
> > try VSCode + https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd
> 
> Does VSCode + clangd work in this case?

![image](https://user-images.githubusercontent.com/39502544/205599639-4d8fdd7b-8e21-41fd-ab53-97d26ab98bf7.png)
Works perfectly fine

**Comment by fannheyward** [comment]
Can you post the full logs of your screenshot? From the beginning.

You doc-example contains some hardcode `cd ~/server/bin/.build && cmake ../src && make` that I can't use it. I'll make a similar project to debug this.

**Comment by fannheyward** [comment]
> Loaded compilation database from /home/ubuntu/server/bin/build/compile_commands.json

clangd already found and loaded the database file.

> ASTWorker building file /home/ubuntu/server/bin/src/include/Framework.h version 1 with command inferred from /home/ubuntu/server/bin/src/main.cpp
[/home/ubuntu/server/bin/build]
/usr/bin/c++ --driver-mode=g++ -I/usr/bin/deps/aws-sdk/bin/include -I/usr/bin/deps/luajit/installation/include/luajit-2.1 -I/home/ubuntu/server/bin/src/include -c -x c++-header -std=gnu++11 -resource-dir=/usr/lib/llvm-14/lib/clang/14.0.0 -- /home/ubuntu/server/bin/src/include/Framework.h

Same as VSCode.

**Comment by fannheyward** [comment]
You can get the logs from `:CocCommand workspace.showOutput clangd`.

Also, you can set `"clangd.trace.server": "verbose"` in your coc-settings.json to get the verbose trace logs.

**Comment by ObiWahn** [comment]
Hi, for me the compilation database feature breaks with this commit:

```
* 5867691 (HEAD) feat: improve clangd.compilationDatabaseCandidates
```

**Comment by ObiWahn** [comment]
This change fixes the problem for me.

```
 173⋮ 175│   private closestCompilationDatabase(candidates: string[]): string {
 174⋮    │-    const expandendCandidates = candidates.map(c => workspace.expand(c));
    ⋮ 176│+    const expandendCandidates = candidates.map(c => workspace.expand(c.replace('${CWD}', workspace.cwd)));
 175⋮ 177 |
```

I am using the following setting in my coc-settings.json: `"clangd.compilationDatabaseCandidates": ["${CWD}-build/current", "${CWD}-build" ,"${CWD}/build"],`

**Comment by fannheyward** [comment]
@ObiWahn sorry for the late response, can you test `"clangd.compilationDatabaseCandidates": ["${cwd}-build/current", "${cwd}-build" ,"${cwd}/build"]`?

Change `CWD` to `cwd`.  coc can expand `${cwd}` to workspace.cwd.

**Comment by ObiWahn** [comment]
`"clangd.compilationDatabaseCandidates": ["${cwd}-build/current", "${cwd}-build" ,"${cwd}/build"]`

Works without issues!

**Comment by fannheyward** [comment]
Close for now.
