### ISSUE TITLE
How to confirm that compile_commands.json and/or compile_flags.txt work?

### ISSUE THREAD

**Issue by gbihtas** [clangd/coc-clangd#55]
Let's assume that we have a directory structure:

foo1/foo2/foo3/src

and a .cpp file in src. I create a compile_commands.json with cmake and store in src. When I start vim I get no feedback whether the compile_commands.json is used or not.

In order to understand its behaviour I take the valid compile_commands.json I have created, let's assume that looks like:

```
[
  { "directory": "/home/user/llvm/build",
    "command": "/usr/bin/clang++ -Irelative -DSOMEDEF=\"With spaces, quotes and \\-es.\" -c -o file.o file.cc",
    "file": "file.cc" },
]
```

and I invalidate it by adding random characters:

```
[
  adfgadgadfadgasdgadga
  { "directory": "/home/user/llvm/build",
    "command": "/usr/bin/clang++ -Irelative -DSOMEDEF=\"With spaces, quotes and \\-es.\" -c -o file.o file.cc",
    "file": "file.cc" },
  ...
]
```

I restart vim or I do `CocRestart` and I get no feedback that something is wrong. Moreover, CocOpenLog or `:CocCommand workspace.showOutput` does not show anything. I have also updated my `.vimrc` with:

`let $NVIM_COC_LOG_LEVEL = 'debug'`

Trying "clangd.trace.server": "verbose" in coc-settings returns that this property is not allowed

Same with compile_flags.txt. No response that it is loaded correctly or that contains errors when I add invalid flags on purpose.

* What if both compile_commands.json and compile_flags.txt are on the same directory. Which one is used?
* What if compile_commands.json is on src directory and compile_flags.txt in foo2? Since it starts searching the parent directories I assume it will find compile_commands.json first and stop searching any more.
* What if compile_commands.json is on src directory and compile_flags.txt in foo2 but compile_commands is invalid? Is it skipped and the compile_flags.txt in foo2 is used?

I try to understand what happens in such scenarios but I have no feedback or log messages to help me on that.

**Comment by kadircet** [comment]
you need to check clangd logs, which can be done through `:CocInfo`. you should see a log line of the form: `Loaded compilation database from xxx`. Whenever clangd loads a compilation database.

Also you can look for a log line of the form `Updating xxx with comand xxx` to see what compile commands clangd is using for a file.

> What if both compile_commands.json and compile_flags.txt are on the same directory. Which one is used?
compile_flags.txt will take precedence.

> What if compile_commands.json is on src directory and compile_flags.txt in foo2? Since it starts searching the parent directories I assume it will find compile_commands.json first and stop searching any more.
We search by going up, so assuming the structure of `foo1/foo2/foo3/src` and a file inside `src/` directory, we'll make use of the compilation database in `src` and stop the search.

> What if compile_commands.json is on src directory and compile_flags.txt in foo2 but compile_commands is invalid? Is it skipped and the compile_flags.txt in foo2 is used?
it depends on your definition of invalid, as long as the file has valid json contents we'll use it. even if the compile commands don't make sense for clang.

**Comment by georgebihtas** [comment]
@kadircet 

Thank you for your reply

* What I mean by "invalid compile_commands.json" is sth like the example I provided. 

```
[
  adfgadgadfadgasdgadga  <<<--- INVALID ENTRY. JSON NO LONGER VALID
  { "directory": "/home/user/llvm/build",
    "command": "/usr/bin/clang++ -Irelative -DSOMEDEF=\"With spaces, quotes and \\-es.\" -c -o file.o file.cc",
    "file": "file.cc" },
  ...
]
```

* I wasn't able to find the `Loaded compilation database` string but I could find the command from the `complile_commands.json` e.g.  `/usr/bin/c++ --driver-mode=g++ -o CMakeFiles/test.dir/solution.cpp.o -c`

* Moreover I could find a `Failed to find compilation database` message if a `complile_commands.json` was not present or was invalid and no "compile_flags.txt" was available as well.

* I could also find the flags from `compile_flags.txt` when `complile_commands.json` was not present.

**Comment by gbihtas** [comment]
@kadircet

Thank you for your reply

*    What I mean by "invalid compile_commands.json" is sth like the example I provided.

[
  adfgadgadfadgasdgadga  <<<--- INVALID ENTRY. JSON NO LONGER VALID
  { "directory": "/home/user/llvm/build",
    "command": "/usr/bin/clang++ -Irelative -DSOMEDEF=\"With spaces, quotes and \\-es.\" -c -o file.o file.cc",
    "file": "file.cc" },
  ...
]

*    I wasn't able to find the Loaded compilation database string but I could find the command from the complile_commands.json e.g. /usr/bin/c++ --driver-mode=g++ -o CMakeFiles/test.dir/solution.cpp.o -c

*    Moreover I could find a Failed to find compilation database message if a complile_commands.json was not present or was invalid and no "compile_flags.txt" was available as well.

*    I could also find the flags from compile_flags.txt when complile_commands.json was not present.

**Comment by kadircet** [comment]
> I wasn't able to find the Loaded compilation database string

Ah, you are right this was introduced right after the branch cut. So it didn't make into clangd-10. You would need to use a weekly build for it, or build from source directly. Weekly builds of clangd can be found at github.com/clangd/clangd/releases
