### ISSUE TITLE
clang-format is not formatting according to .clang-format

### ISSUE THREAD

**Issue by romch007** [clangd/coc-clangd#574]
Whenever I save a C++ file, the file is formatted using default style, and not using the style is the `.clang-format` file. The `.clang-format` file is located at the root of the project.

**Logs**
I don't know how to get logs.

**System information**
Clangd version (from the log, or `clangd --version`):
```
clangd version 15.0.7
Features: linux
Platform: x86_64-pc-linux-gnu
```
clangd extension version (from `:CocInfo`): `0.28.0`
Operating system: `Arch Linux 6.2.10-arch1-1`

**Comment by fannheyward** [comment]
Looks like clangd didn't find and use the `.clang-format` file. coc-clangd didn't touch the clang-format, it's clangd's issue, you can try set `.clang-format` global in `~/config/clang-format/.clang-format`.

**Comment by fannheyward** [comment]
https://clangd.llvm.org/features#formatting
