### ISSUE TITLE
hover doesn't work properly

### ISSUE THREAD

**Issue by CODESOLE** [clangd/coc-clangd#58]
when i press shift + k at first it works but after second, third, .... and so on it doesn't show proper string. 

**System information**
Output of `clangd --version`:  clangd version 10.0.0-4ubuntu1 
Editor/LSP plugin: vim coc-clangd
Operating system: kubuntu 20.04
![issue](https://user-images.githubusercontent.com/22984206/83554454-74c22c00-a515-11ea-9f9c-d02821bf8828.gif)

**Comment by sam-mccall** [comment]
There was a coc.nvim bug around floats in vim that I believe has been fixed. Can you update coc.nvim and see if you can still reproduce this?

**Comment by CODESOLE** [comment]
I updated but unfortunately still issue continuing :(

**Comment by fannheyward** [comment]
`coc.nvim version: 0.0.78-fd9e7d3972` is about month early version, please upgrade your coc.nvim.
