### ISSUE TITLE
How to select the suggested autocomplete?

### ISSUE THREAD

**Issue by itamavig** [clangd/coc-clangd#586]
When trying the autocomplete, pressing `Enter` does line break (and closing the autocomplete suggestions ) instead of applying the marked suggestion

![image](https://user-images.githubusercontent.com/66136589/236496248-fdeb2648-6148-4f3a-a7ee-4852357924a5.png)

**Comment by fannheyward** [comment]
You need to map your `<cr>`, check coc.nvim's README.
