### ISSUE TITLE
There is a little issue with coc-clangd in termux.

### ISSUE THREAD

**Issue by DuilioPerez** [clangd/coc-clangd#593]
# In Neovim running in termux the name of the arugments are shown in a wrong way.
I've used the plugin coc-clangd for Vim and, recently, Neovim. In vim there is no issues, only that sometimes the server is stopped. In Neovim, arguments are show wrong.
# Vim screenshot:
![cocClangdVim](https://github.com/clangd/coc-clangd/assets/135564120/0dda44d6-0c4d-462b-bb41-a29146d5bae8)
Here does work correctly!

# Neovim screeshot:
![cocClangdNvim](https://github.com/clangd/coc-clangd/assets/135564120/8c49237f-099a-47b4-9815-c00c05240c65)

Parameters are shows after the functions.

**System information**
Clangd version (from the log, or `clangd --version`):
clangd version 16.0.5
Features: linux
Platform: aarch64-unknown-linux-android24

Coc.nvim version: coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800

Operating system:
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=8735
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
11
Kernel build information:
Linux localhost 4.14.186-22735277 #1 SMP PREEMPT Sat Feb 19 02:14:57 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A225M
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.x11 versionCode:11
com.termux.styling versionCode:29

**Comment by fannheyward** [comment]
nvim can't display _inline_ inlayHint for now, can only display at the end of line. The nightly nvim has added this, no stable release yet.
