### ISSUE TITLE
Question: How to setup coc-clangd to format vector<vector<int> > instead of vector<vector<int>>

### ISSUE THREAD

**Issue by SUPERustam** [clangd/coc-clangd#594]
I have code in `.cpp`:
```cpp
...
vector<   vector <int>      >  a;
...
```
After `coc-clangd`:
```cpp
...
vector<vector<int>>  a;
...
```
But I want this (because my compiler doesn't understand `vector<vector<int>>` without space between last brackets
```cpp
...
vector<vector<int> >  a;
...
```

Which configs I should setup in config files to resolve this issue?

**Comment by sam-mccall** [comment]
`Standard: c++03` in your `.clang-format` file.

https://clang.llvm.org/docs/ClangFormatStyleOptions.html#standard

**Comment by SUPERustam** [comment]
Thank you, @sam-mccall !

**Comment by g0t4** [comment]
@sam-mccall do you know if there is a way to set formatting options via `coc-settings.json` for global defaults? Or is it only `.clang-format` repo level settings?
