### ISSUE TITLE
Code completion doesn't respect allCommitCharacters

### ISSUE THREAD

**Issue by kadircet** [clangd/coc-clangd#6]
Here's the documentation from lsp spec:
```
	/**
	 * The list of all possible characters that commit a completion. This field can be used
	 * if clients don't support individual commit characters per completion item. See
	 * `ClientCapabilities.textDocument.completion.completionItem.commitCharactersSupport`.
	 *
	 * If a server provides both `allCommitCharacters` and commit characters on an individual
	 * completion item the ones on the completion item win.
	 *
	 * @since 3.2.0
	 */
	allCommitCharacters?: string[];
```

clangd started sending this out in its `completionProvider` field recently, but it seems like CoC doesn't fall back to `allCommitCharacters` when `completionItem` doesn't have individual commit characters.

This results in only being able to commit a completion with hitting enter.

**Comment by fannheyward** [comment]
Correct me if I'm wrong. coc already added [`commitCharactersSupport`](https://github.com/neoclide/coc.nvim/blob/3c462c6486725f7e3a82900e75c671d5d31bf093/src/language-client/client.ts#L1702), but not fallback to use `allCommitCharacters`?

**Comment by kadircet** [comment]
right, as @sam-mccall pointed out in an offline discussion the logic in https://github.com/neoclide/coc.nvim/blob/master/src/languages.ts#L651 doesn't take `allCommitCharacters` into account when there's none send with the completionitem.

**Comment by fannheyward** [comment]
I'll check coc side. But first I needed to download clangd HEAD build, do you known anywhere provides a nightly build download?

**Comment by sam-mccall** [comment]
No worries, I think I just about have a patch for this. The style might be wrong but I have to learn sometime :-)

For future: https://github.com/clangd/clangd/releases has weekly snapshots (well, one so far, just got it working).
But the build is from a couple of days ago, and the allCommitCharacters patch landed literally today in LLVM.

**Comment by sam-mccall** [comment]
https://github.com/neoclide/coc.nvim/pull/1565/files

**Comment by fannheyward** [comment]
Merged.
