### ISSUE TITLE
Connection is disposed

### ISSUE THREAD

**Issue by zlianon** [clangd/coc-clangd#60]
### session
https://asciinema.org/a/mMoz3YPbQ7oxNaFsjhoYYSBoF

### log
https://gist.github.com/zlianon/fa6ebbaf296c97c2ca7cce73e033b663

### coc-settings.json
```json
{
    "coc.preferences.extensionUpdateCheck": "never",

    "coc.source.around.enable": false,
    "coc.source.buffer.enable": false,

    "diagnostic.enable": false,

    "suggest.minTriggerInputLength": 2,
    "suggest.timeout": 15000,

    "clangd.showDBChangedNotification": false,
    "clangd.arguments": [
        "--header-insertion=never",
        "--limit-results=50",
        "--log=verbose"
    ],
    "clangd.fallbackFlags": [
        "-std=c++17"
    ]
}
```

### coc-extensions
```vim
let g:coc_global_extensions = [
    \ 'coc-clangd',
    \ 'coc-cmake',
    \ 'coc-json'
    \]
```

**Comment by fannheyward** [comment]
Do you have `languageserver.clangd` config in coc-settings.json? Something like this https://github.com/neoclide/coc.nvim/wiki/Language-servers#ccobjective-c

**Comment by zlianon** [comment]
@fannheyward  No, this is my coc-settings configuration:
```json
{
    "coc.preferences.extensionUpdateCheck": "never",

    "coc.source.around.enable": false,
    "coc.source.buffer.enable": false,

    "diagnostic.enable": false,

    "suggest.minTriggerInputLength": 2,
    "suggest.timeout": 15000,

    "clangd.showDBChangedNotification": false,
    "clangd.arguments": [
        "--header-insertion=never",
        "--limit-results=50",
        "--log=verbose"
    ],
    "clangd.fallbackFlags": [
        "-std=c++17"
    ]
}
```

**Comment by fannheyward** [comment]
What's your `:CocList services` when you open C++ files? From your screencast, there is an error message `Looks like you've configured clangd in coc-settings.json, you should remove it to use coc-clangd`.

**Comment by zlianon** [comment]
More details: https://asciinema.org/a/I8gbBYjQuhqGhprDFn5P7nIiL

![2020-06-08-120939_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/84018951-f20bf780-a980-11ea-8e6a-70a270e5e505.png)

**Comment by fannheyward** [comment]
Looks like it's reloading clangd failed. I've tested with this demo, works as except:

main.cc:

```c
int main() {
    return 0;
}
```

CMakeLists.txt:

```
project(t1)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_EXPORT_COMPILE_COMMANDS TRUE)
add_executable(t1 src/main.cc)
```

**Comment by fannheyward** [comment]
I've reworked the reload logic, please try v0.4.8.

**Comment by zlianon** [comment]
@fannheyward Same, but i tried to reload manually clangd and i get this error from latest coc.nvim:

![2020-06-08-130712_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/84023761-f9cf9a00-a988-11ea-84dc-5ca2a9fd7439.png)

`Error detected while processing function coc#rpc#restart[4]..coc#util#close_floats:                                                                                                                           
line    5:                                                                                                                                                                                                    
E117: Unknown function: nvim_win_get_config                                                                                                                                                                   
E116: Invalid arguments for function empty                                                                                                                                                                    
E15: Invalid expression: !empty(nvim_win_get_config(id)['relative'])                                                                                                                                          
client coc stopped!                                                                                                                                                                                           
starting coc.nvim service`
