### ISSUE TITLE
Refactoring Features

### ISSUE THREAD

**Issue by rockwotj** [clangd/coc-clangd#609]
Hello, I know that recent versions of clangd can do things like generate constructors, copy/move constructors, etc. Here's an example of some of them: https://main--clinquant-entremet-9c06af.netlify.app/features#generate-member-wise-constructor

How can we use some of those features in coc?

Here's a list of the ones I'm personally interested in:
- Generating constructors
- expanding auto types
- extract function

**Comment by fannheyward** [comment]
Looks like you can make it with codeAction.
