### ISSUE TITLE
stdint.h Library error

### ISSUE THREAD

**Issue by RickyOwings** [clangd/coc-clangd#610]
I had this weird bug with coc-clangd. I was creating a project with SDL3 and it did not like the header. I thought this was weird at first. I then went digging through the header file for SDL3 and found that the error was coming from <stdint.h>

![image](https://github.com/clangd/coc-clangd/assets/110073156/2eb13179-fa57-4cd1-a013-af3d8b535d4c)

I then linked the stdint library to my project and I got the same error within my project.

![image](https://github.com/clangd/coc-clangd/assets/110073156/cd8fcc4d-f955-447e-a343-946db16487c5)

The strange thing is that it only did it with stdint.h, not any other library

![image](https://github.com/clangd/coc-clangd/assets/110073156/5da995c8-1754-4ee2-a54c-e9cca442e8b5)

I later then installed clangd with sudo apt install clangd. After running :CocConfig, I set the "clangd.path" to "/usr/bin/clangd" and this seemed to fix the issue.

Originally, when I installed coc-clangd, I used the :CocCommand clangd.install command to get clangd. There might be some issue with the command. I am having a hard time reproducing the error right now for some reason. 

Thought I would post my error here just in case it would help you guys! I am not the most knowledgeable when it comes to Neovim, and it very well could have been something to do with my configuration. It would be great if this helps!

**Comment by fannheyward** [comment]
Looks like the `clangd` installed by `:CocCommand clangd.install` is broken. https://github.com/clangd/coc-clangd/issues/577
