### ISSUE TITLE
Question: navigate to conflicting item/item causing error?

### ISSUE THREAD

**Issue by klement** [clangd/coc-clangd#611]
Hi,

I'm quite frequently facing an issue where I get an error in a file, but the real cause is in a different file and I can't find a way to navigate from one to another.

Example of such error is "Static declaration of 'XYZ' follows non-static declaration (clang static_non_static)".

It's cool that it points out this error, but it'd be even cooler if one could jump from this error to the other (conflicting) place.

Clang(d) obviously knows about the conflicting place:

> In file included from /home/ksekera/x.c:1:
> /home/ksekera/x.h:296:1: error: static declaration of 'find_tag' follows non-static declaration
> find_tag (uint32_t *val)
> ^
> /home/ksekera/y.h:103:5: note: previous declaration is here
> int find_tag(uint32_t *);
>     ^
> 

It's not a problem if it's within the same file, but if it's in a different file I couldn't find any coc-* method to do that.

Does such a method exist?

Thanks!

**Comment by fannheyward** [comment]
> could jump from this error to the other (conflicting) place

This needs `clangd` to provide location of conflicting in some way, coc.nvim/coc-clangd is LSP client, it jumps to the location provided by LS.

**Comment by sam-mccall** [comment]
@fannheyward for clang notes like this, clangd should be providing the location as relatedInformation on the diagnostic.

(I haven't verified it does so in this specific case)

**Comment by fannheyward** [comment]
> providing the location as relatedInformation on the diagnostic.

@klement you can enable `diagnostic.separateRelatedInformationAsDiagnostics` to list relatedInformations as diagnostics

**Comment by klement** [comment]
Thanks! that's perfect!
