### ISSUE TITLE
clangd don't start on windows

### ISSUE THREAD

**Issue by TrickB0y** [clangd/coc-clangd#621]
lately when i try to reinstall coc-clangd completion on windows (this has happened more than once) after run ':CocInstall coc-clang' and 
'CocCommand clangd.install' i get the error: '[coc.nvim] Server clangd failed to start: Error: spawn UNKNOWN'.
i searched on internet i got some people with same issue. i know i need to have clangd in path but the clangd copy downloaded by coc is broken so i installed the whole LLVM and add the bin folder to path but still gotting the same error, even if i delete the coc copy of clangd. so i swaped places of coc copy on AppData folder  with LLVM copy and it worked.
now completion its running just fine but i has downloaded the LLVM original file to work. this don't make any sense to me.

**Comment by fannheyward** [comment]
1. delete the clangd downloaded by coc-clangd
2. `CocUpdate` to upgrade coc-clangd to v0.29.3
3. `CocCommand clangd.install` again to install clangd.
