### ISSUE TITLE
Unable to locate C/C++ header files (stdio.h, etc.)

### ISSUE THREAD

**Issue by dduyanhhoang** [clangd/coc-clangd#622]
I have just setup neovim using [kickstart nvim](https://github.com/nvim-lua/kickstart.nvim) on a windows machine.

I'm quite clueless about how to properly config the path to gcc (installed with scoop) using [query drivers](https://clangd.llvm.org/guides/system-headers#query-driver), either [adding table to coc-settings.json](https://github.com/clangd/coc-clangd/issues/313#issuecomment-889595229) cause I'm unable to locate it either where to fit it in the kickstart file system.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/137117837/265888401-6aaeada2-b984-462c-822d-9deadea962d5.png">

**Comment by fannheyward** [comment]
You need to set it in Lua.
