### ISSUE TITLE
some error flag but the code can running

### ISSUE THREAD

**Issue by sngkhiem** [clangd/coc-clangd#631]
<img width="255" alt="image" src="https://github.com/clangd/coc-clangd/assets/58633954/8db784ef-d901-49c1-8d4c-757684d7b74f">
I just installed clangd and got the thing in the photo, why it highlight my code in red without any error of my code

**Comment by fannheyward** [comment]
You need to setup compile_commands.json to make clangd to understand your code.

https://clangd.llvm.org/installation#project-setup
