### ISSUE TITLE
 How do I remove the automatically added parameter label in parentheses?

### ISSUE THREAD

**Issue by wenxingguo** [clangd/coc-clangd#632]
When I upgraded clangd, the function parameter label was automatically added in the parentheses of the function call in my C++ code. How can I remove it?
![](https://raw.githubusercontent.com/wenxingguo/pcl_img/b5478a1f928ce087528575bccb42606fd9a3f175/%E6%88%AA%E5%B1%8F2023-10-13%2014.28.28.png)

**System information**
Clangd version (from the log, or `clangd --version`):
clangd 15 
clangd extension version (from `:CocInfo`):

Operating system:
debian 12 and macos

**Comment by fannheyward** [comment]
It's inlay hints. Check `:h coc-inlayHint` and `:h coc-config-inlayHint`.
