### ISSUE TITLE
An issue of including libraries

### ISSUE THREAD

**Issue by huanmoon** [clangd/coc-clangd#633]
I'm writing a c plus plus program with ncurses.h
the functions in this library are very similar to curses.h, so clangd include <curses.h> automaticlly
but I just want to use ncurses.h not curses.h
![image](https://github.com/clangd/coc-clangd/assets/63947748/7043d815-ea3d-4885-914e-5f3c481b6b2e)

![image](https://github.com/clangd/coc-clangd/assets/63947748/9f3dbe05-01e7-4150-8e69-27697d63adeb)

**Comment by fannheyward** [comment]
clangd's issue, needs clangd return correct completion item.

**Comment by huanmoon** [comment]
> clangd's issue, needs clangd return correct completion item.

excuse me but what is clangd return

**Comment by fannheyward** [comment]
The return from clangd contains `<curses.h>`, coc just apply and insert it to document.

**Comment by huanmoon** [comment]
> The return from clangd contains `<curses.h>`, coc just apply and insert it to document.

then how to correct it

**Comment by fannheyward** [comment]
Needs clangd to fix this.

**Comment by huanmoon** [comment]
> Needs clangd to fix this.

so you mean, I can't use coc-clangd if I want to fix this issue?

**Comment by fannheyward** [comment]
coc/coc-clangd is client, the clangd server returns the completions, client just accepts and adds to your document. If the completion item is not correct, needs the clangd server to fix and returns correct ones.

**Comment by huanmoon** [comment]
> coc/coc-clangd is client, the clangd server returns the completions, client just accepts and adds to your document. If the completion item is not correct, needs the clangd server to fix and returns correct ones.

I installed clangd and I put the right path of clangd in CocConfig.json, coc-clangd will start clangd server automaticlly too (When I am editing a cpp file,  'pidof clangd' can return a correct value.) But the issue is not solved.It still will include curses.h automaticlly.

**Comment by fannheyward** [comment]
clangd is working but not correctly, this must be fixed in _clangd_ itself.
