### ISSUE TITLE
Duplicate references

### ISSUE THREAD

**Issue by hexhexD** [clangd/coc-clangd#639]
I'm using the latest 17.0.5 clangd, not sure if it's a clangd or coc.nvim issue.

![image](https://github.com/clangd/coc-clangd/assets/6869543/95e78b61-0276-4a5f-94ac-bf17d1c54ea7)
![image](https://github.com/clangd/coc-clangd/assets/6869543/708a4dd3-8d3f-4bc5-a09d-aab7e19ab47f)

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

**Logs**
Please attach the clangd log from `:CocCommand workspace.showOutput` if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

**System information**
Clangd version (from the log, or `clangd --version`):
clangd extension version (from `:CocInfo`):
Operating system:

**Comment by fannheyward** [comment]
The locations were returned by clangd, looks like clangd duplicate them.

Set `"clangd.trace.server": "verbose"` and check trace logs `:CocCommand workspace.showOutput clangd`.

**Comment by hexhexD** [comment]
Yeah, I'm seeing the same range 3 times in the [Trace - 07:18:34.490] Received response 'textDocument/references - (23)' in 1ms.
Result: [`
