### ISSUE TITLE
这个插件如何在补全头文件比如#include<iostream>时，光标在>的右边，否则每次都多跳过这个符号一次

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [clangd/coc-clangd#656]
Note: we mostly implement features in the clangd language server, and rely on coc.nvim's LSP client framework to expose these in vim. Features requiring a lot of coc-specific work are unlikely to be implemented.

**Comment by fannheyward** [comment]
clangd 返回的 snippet 是 `include <$0>`，光标会在尖括号中间，只能手动跳过。
