### ISSUE TITLE
Connection to server got closed

### ISSUE THREAD

**Issue by SHAHNUR00** [clangd/coc-clangd#659]
After running the command `clangd --version ` it is giving the following output:
![Screenshot (10)](https://github.com/clangd/coc-clangd/assets/109983076/13cd17ca-912b-4bcb-bdd9-f908e274c708)
<br>
And I also make sure that **clangd is in my $PATH**
![Screenshot (11)](https://github.com/clangd/coc-clangd/assets/109983076/2cac15e8-f9a7-4420-8880-7162e4c932ad)

**I did all of the stuffs before creating this issue**

**Comment by fannheyward** [comment]
The clangd server failed to start, coc-clangd is a client and can do nothing about this.
