### ISSUE TITLE
coc-clangd unable to get local issuer certificate.

### ISSUE THREAD

**Issue by priyanshu219** [clangd/coc-clangd#66]
When I type **:CocInstall coc-clangd**, then it shows error:
```
✗ coc-clangd unable to get local issuer certificate
```

Also, in case of **:CocCommand clangd.install**, then it shows that:
```
[coc.nvim] Command: clangd.install not found
```
So how can I fix this?

**Comment by fannheyward** [comment]
Does your network behind a proxy? It's not coc or coc-clangd issue. Try add `"http.proxyStrictSSL": false` to your coc-settings.json and try again.
