### ISSUE TITLE
coc-clangd没有输入头文件的情况下也能补全

### ISSUE THREAD

**Issue by djfyz** [clangd/coc-clangd#662]
配置好coc-clangd后，明明没有输入任何头文件，结果各种补全就出来了
想实现的效果时，根据输入的头文件补全，应该怎么设置啊
![screenshot-20240313-104658](https://github.com/clangd/coc-clangd/assets/8026734/8201ce3f-4cf3-4de9-aaa5-4847d5c1b05b)

**Comment by fannheyward** [comment]
Add `-header-insertion=never` to clangd, check https://github.com/clangd/clangd/issues/55

**Comment by djfyz** [comment]
已经加了这个参数，目前看这个参数只是保证了不会自动添加头文件，但我遇到的问题时，在一个空的C文件里，输入一个"p"后，补全了一堆头文件里面的内容，但此时我还没有包含任何的头文件

刚试了下vs code，是符合预期的，补全的信息是随着头文件走的

**Comment by fannheyward** [comment]
@djfyz 你 VSCode 也是 clangd 吗？可以对照一下参数是否一致，这个补全项是 clangd 提供的。

**Comment by djfyz** [comment]
嗯嗯，乌龙了，vscode上切成clangd补全后也是这表现，换成coc-ccls后，符合预期了~
