### ISSUE TITLE
Disable code formating on coc-rename

### ISSUE THREAD

**Issue by markodevv** [clangd/coc-clangd#67]
is there a way to turn off code formating when using coc-rename? Or can i change the style of the format?

**Comment by sam-mccall** [comment]
> is there a way to turn off code formating when using coc-rename

Not yet, but soon - once the config system lands we'd like to add a setting to disable implicit formatting.

> Or can i change the style of the format?

`.clang-format` files should be respected.

**Comment by 3vilStar** [comment]
You can add `--fallback-style=none` in `clangd.arguments`

**Comment by kirillbobyrev** [comment]
Related Clangd issue: https://github.com/clangd/clangd/issues/271

**Comment by fannheyward** [comment]
clangd's issue.
