### ISSUE TITLE
It can support like [c-mantic] feature?

### ISSUE THREAD

**Issue by arashrun** [clangd/coc-clangd#673]
This the [c-mantic](https://bigbahss.github.io/vscode-cmantic/) website.

features like:

[Add Definition](https://bigbahss.github.io/vscode-cmantic/features/add-definition/)
[Add Declaration](https://bigbahss.github.io/vscode-cmantic/features/add-declaration/)
[Update Function Signature](https://bigbahss.github.io/vscode-cmantic/features/update-function-signature/)
[Move Definition](https://bigbahss.github.io/vscode-cmantic/features/move-definition/)

**Comment by fannheyward** [comment]
No such features, and no plan to support for now.
