### ISSUE TITLE
launch server clangd using command failed

### ISSUE THREAD

**Issue by Elite-zx** [clangd/coc-clangd#678]
My clangd has been running very well. However, after I ran the command clangd.install, I encountered the following issue.
<img width="1772" alt="image" src="https://github.com/clangd/coc-clangd/assets/110723979/b120e194-cb99-41e6-9966-709881f1bfc5">
My coc-settings are as follows:
<img width="741" alt="image" src="https://github.com/clangd/coc-clangd/assets/110723979/d07b22ed-9eb7-407c-a0ef-2e6740461da6">

my system aleady install clangd, and works fine :
<img width="1387" alt="image" src="https://github.com/clangd/coc-clangd/assets/110723979/6230d3d4-3b71-43e7-a0aa-3af97beaf476">

**Comment by fannheyward** [comment]
1. you don't need to setup `clangd` in coc-settings.json when using coc-clangd
2. your first screenshot shows the clangd v18.1.3 couldn't run on your OS, maybe this version  is not compatible, you can manually install clangd, and set `clangd.path` in your coc-settings.json to be used by coc-clangd.

**Comment by Elite-zx** [comment]
> which clangd
> /usr/local/bin/clangd

What should be done specifically， my coc-settings.json :
<img width="638" alt="image" src="https://github.com/clangd/coc-clangd/assets/110723979/ad4530f0-cf3a-41ac-a226-878d4af46734">

the problem still exists

**Comment by fannheyward** [comment]
Put `clangd.path` in the root section

<img width="372" alt="image" src="https://github.com/clangd/coc-clangd/assets/345274/d3e5eda2-336f-4a19-b3b9-4f53e71c4e06">

**Comment by Elite-zx** [comment]
same error when I open .cpp file:
<img width="1784" alt="image" src="https://github.com/clangd/coc-clangd/assets/110723979/8e2ca143-b321-4d84-89d8-c4e260851af3">


my coc-settings.json :

<img width="535" alt="image" src="https://github.com/clangd/coc-clangd/assets/110723979/ed1b8be3-fa40-4155-be9f-d1849c50ef96">


CocInfo:
## versions

vim version: VIM - Vi IMproved 8.2 8022520
node version: v17.9.1
coc.nvim version: 0.0.82-c3ae5c3b 2024-05-23 20:39:40 +0800
coc.nvim directory: /data/zenonzhang/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2024-06-05T20:12:51.742 INFO (pid:12826) [plugin] - coc.nvim initialized with node: v17.9.1 after 181
2024-06-05T20:12:52.974 INFO (pid:12826) [services] - LanguageClient clangd state change: stopped => starting
2024-06-05T20:12:52.979 INFO (pid:12826) [services] - LanguageClient clangd state change: starting => stopped
2024-06-05T20:12:52.980 ERROR (pid:12826) [services] - Server clangd failed to start: Error: Launching server "clangd" using command ../../../.config/coc/
extensions/coc-clangd-data/install/18.1.3/clangd_18.1.3/bin/clangd failed.
  ¦ at /data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:75028:37
  ¦ at async LanguageClient.createConnection (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:74368:28)
  ¦ at async LanguageClient._start (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:73999:30)
  ¦ at async Object.start (/data/zenonzhang/.vim/plugged/coc.nvim/build/index.js:75518:17)
2024-06-05T20:12:57.048 INFO (pid:12826) [attach] - receive notification: showInfo []



this annoying problem occured after I run clangd.install @v@

**Comment by fannheyward** [comment]
You can remove this `~/.config/coc/
extensions/coc-clangd-data/install/18.1.3/clangd_18.1.3/bin/clangd`.
