### ISSUE TITLE
The false branch of #if is not grayed out.

### ISSUE THREAD

**Issue by LendyZhang** [clangd/coc-clangd#69]
Semantic highlighting is disable between the false branch of #if/#endif, however it's better to have those code grayed out.

**Comment by fannheyward** [comment]
It's not a bug, no such feature yet.

**Comment by oblitum** [comment]
This works for me.

**Comment by oblitum** [comment]
Ah Okay, now I got it... Indeed, there's no "graying out" just turn off. Actually I wonder whether graying  out is even possible in vim/neovim, I think there's no such feature in the editor itself.

**Comment by oblitum** [comment]
Hmmm, it may be possible to implement on NeoVim using an empty floating window with `&winblend` set to some transparency value.

**Comment by mellery451** [comment]
Maybe I'm misunderstanding the issue, but I believe https://github.com/clangd/clangd/issues/132 is related. According to the most recent comment there, clangd-11 should support this, although possibly some client changes are required (?) - https://github.com/clangd/vscode-clangd/pull/54/files

**Comment by oblitum** [comment]
@mellery451 there's no graying-out capability on [neo]vim. It's possible to fake it on neovim through an overlay window as commented before, but I think it's hard to implement. Basic single-tone "graying out" already works.

**Comment by mellery451** [comment]
sorry to change the subject, but are there docs on how to get the "basic" (comment lowlight) option working with clangd? I can make it work if I use ccls as the LS, but never have been able to get it working with clangd, even if I use clangd-11

**Comment by oblitum** [comment]
> "basic" (comment lowlight)

I get that by enabling semantic highlighting by integrating with vim-lsp-cxx-highlight, as commented in README.

**Comment by mellery451** [comment]
yeah, that has never worked for me. It works as soon as I enable ccls in coc.nvim, but with clangd alone, I never get the disabled region shown as such. I've tried with every available version of clangd.

**Comment by oblitum** [comment]
@mellery451 no idea why it doesn't work for you...

**Comment by kirillbobyrev** [comment]
> Maybe I'm misunderstanding the issue, but I believe [clangd/clangd#132](https://github.com/clangd/clangd/issues/132) is related. According to the most recent comment there, clangd-11 should support this, although possibly some client changes are required (?) - https://github.com/clangd/vscode-clangd/pull/54/files

If I understand correctly, the inactive code ranges were added very recently (https://github.com/llvm/llvm-project/commit/0aaa2acc4ca0389a79a46bca3dc5b9365c641d77#diff-bc83abf3e556418f438c09a672856449) so you might need this patch for such functionality. It didn't make it into any release yet, so I think the only way it would work would be a nightly release via clangd/clangd Releases.

@hokein might have more context and correct me if I am wrong.

**Comment by hokein** [comment]
clangd-10 supports inactive region partially, it sends `InactiveCode` token, but without computed ranges (the original plan was required special handling in all client side), so the current [implementation](https://github.com/clangd/coc-clangd/blob/master/src/semantic-highlighting.ts#L87) doesn't gray out the inactive region.

Yeah, with the patch https://github.com/llvm/llvm-project/commit/0aaa2acc4ca0389a79a46bca3dc5b9365c641d77, it should just work with coc-clangd, but you need a weekly-build [clangd](https://github.com/clangd/clangd/releases).

**Comment by oblitum** [comment]
My clangd version is 10.0.1 and anytime I write `#if 0` it grays out the code.

**Comment by oblitum** [comment]
![screencast](https://user-images.githubusercontent.com/1269815/91880576-b074ab00-ec56-11ea-8ca1-4f9df8545f7f.gif)

**Comment by oblitum** [comment]
Looks like that just works for `#if 0`, for `#if 1 < 0` it doesn't.

**Comment by mellery451** [comment]
@oblitum that `#if 0` thing comes from the c syntax file (`:help c.vim`) because it's so common for c progs to block comment with it. It has nothing to do with actual preprocessor/compiler info.

**Comment by oblitum** [comment]
hmm, ok, my bad then.

**Comment by mellery451** [comment]
clangd-11 is released and I believe the patch that @hokein mentions above should be included. What else needs to be done to enable this with coc-clangd? Or is this strictly dependent on vim-lsp-cxx-highlight to support it?

**Comment by fannheyward** [comment]
> is this strictly dependent on vim-lsp-cxx-highlight to support it?

Yes, `vim-lsp-cxx-highlight` is needed for semantic highlighting by now.

coc will add semanticTokens support, https://github.com/neoclide/coc.nvim/pull/2756, `vim-lsp-cxx-highlight` is not needed anymore. Bellow screenshots don't use vim-lsp-cxx-highlight.

<img width="213" alt="截屏2021-02-19 18 34 11" src="https://user-images.githubusercontent.com/345274/108493258-11656d80-72e1-11eb-9755-1136d5dff411.png">
<img width="244" alt="截屏2021-02-19 18 35 19" src="https://user-images.githubusercontent.com/345274/108493395-3954d100-72e1-11eb-8e4e-1dd1304a03ae.png">

**Comment by mellery451** [comment]
good news - thanks. I want to suggest NOT using `#if 0` to test this feature, however...as I mentioned above, that particular construct has been part of the c-syntax file in vim for years so you might be fooled into thinking highlighting/lowlighting is working with that when in fact it's just the syntax file doing it. Better to use something like `#ifdef _DEBUG` or something like that.
