### ISSUE TITLE
How to remove template type in completion

### ISSUE THREAD

**Issue by xyz1001** [clangd/coc-clangd#690]
How to remove template type when completion? For example, when I type "std::unique_ptr" and press tab, it will complete to "std::unique_ptr<typename Tp>". I do not want the "typename Tp".

**Logs**
Please attach the clangd log from `:CocCommand workspace.showOutput` if you can.
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!

[clangd.log](https://github.com/user-attachments/files/16705323/clangd.log)

**System information**
Clangd version (from the log, or `clangd --version`): 17.0.6
clangd extension version (from `:CocInfo`): 
vim version: NVIM v0.10.0
node version: v22.2.0
coc.nvim version: 0.0.82-bd303cf7 2024-03-01 18:31:10 +0800
coc.nvim directory: /home/xyz1001/.local/share/nvim/lazy/coc.nvim
term: tmux
platform: linux
Operating system: Arch in WSL2 and Windows11 and macos 14.6

**Comment by fannheyward** [comment]
It's called inlayHint, you can disable it by setting `inlayHint.enable` to false in your coc-settings.json, check `:h coc-config-inlayHint`

**Comment by xyz1001** [comment]
![image](https://github.com/user-attachments/assets/77c1b445-e2e2-43e7-86c9-9b64e53d520d)
My problem  is not the hint( the `n: ` in the picture), but the template types(`<typename Tp>` in the picture).

**Comment by fannheyward** [comment]
It's from clangd, you should check the server on how to disable it.
