### ISSUE TITLE
diagnostics floats are really noisy

### ISSUE THREAD

**Issue by sam-mccall** [clangd/coc-clangd#7]
Currently I see:
`[clang(Semantic Issue) ovl_no_viable_function_in_call] [E] No matching function for call to 'foo'`

The diagnostic text is the most important but it starts on column 59, and is the first thing to get truncated/wrapped.

A big contributor is clang/clangd which use long strings for the code. I think they have some value but display needs to be done carefully.

Another contributor is the (Semantic Issue) category, which I'm not sure is pulling its weight.

I'd like to try making the source/code styled differently, placed at the end of the diagnostic, and dropping the [E] in upstream coc.

**Comment by fannheyward** [comment]
The diagnostic format is defined `[source code] [severity] message` in https://github.com/neoclide/coc.nvim/blob/3c462c6486725f7e3a82900e75c671d5d31bf093/src/diagnostic/manager.ts#L306. coc needs to add diagnostic format support.

**Comment by kadircet** [comment]
btw, we might also consider moving the `full` diagnostic info to the command line and only show diagnostic message in the floating window.

I also think it would be better if diag(floating window) hasn't moved with the cursor, it could pop-up once the user enters diag range and stay there until user exits it.

**Comment by sam-mccall** [comment]
> I also think it would be better if diag(floating window) hasn't moved with the cursor, it could pop-up once the user enters diag range and stay there until user exits it.

Yeah, I don't know if this is easy/hard to do.
I do find myself wishing it was pinned to column zero instead of anchored at the cursor, because it tends to truncate or wrap.

**Comment by fannheyward** [comment]
> I also think it would be better if diag(floating window) hasn't moved with the cursor

If you are using Neovim, add `"diagnostic.virtualText": true` to `coc-settings.json`, the diagnostic message will pinned with virtual text at the end of line.

**Comment by sam-mccall** [comment]
Thanks for the pointer. I think that's the one for preview window, and this one is for floating windows:
https://github.com/neoclide/coc.nvim/blob/3c462c6486725f7e3a82900e75c671d5d31bf093/src/diagnostic/manager.ts#L458

(Some of the concerns apply to both, but space is much less of a concern in the preview window for instance)

> If you are using Neovim, add "diagnostic.virtualText": true to coc-settings.json, the diagnostic message will pinned with virtual text at the end of line.

This is nice - I tried it out, but one of our goals is to support a bunch of internal users who are using a particular version of vim (fairly recent: 8.1.2269).

**Comment by sam-mccall** [comment]
So while customizability (and highlighting) is nice, playing with this makes me more convinced that the defaults can be improved first. Does this seem more readable

Before:
![image](https://user-images.githubusercontent.com/548993/74845269-0c1cbe00-532f-11ea-93d9-0c5e1988908a.png)
![image](https://user-images.githubusercontent.com/548993/74845283-12129f00-532f-11ea-8089-8f0e0f61387b.png)

After:
![image](https://user-images.githubusercontent.com/548993/74845295-176fe980-532f-11ea-9b64-0027399c76ed.png)
![image](https://user-images.githubusercontent.com/548993/74845305-1b9c0700-532f-11ea-91e1-47f351911d22.png)

**Comment by sam-mccall** [comment]
@kadircet points out that floating windows use a different color per severity, as well as the gutter marker, and the `Error: ` is mostly noise:

![image](https://user-images.githubusercontent.com/548993/74845806-ce6c6500-532f-11ea-90ae-4bcf7faf3dba.png)
![image](https://user-images.githubusercontent.com/548993/74845812-d1ffec00-532f-11ea-8e0f-f3526ebb1561.png)

**Comment by sam-mccall** [comment]
https://github.com/neoclide/coc.nvim/pull/1564

**Comment by fannheyward** [comment]
Changed on coc by adding `diagnostic.format`, without change the default style. User can define format they want, eg drop the `source` part.

**Comment by sam-mccall** [comment]
Thanks for doing that! 
Having it customizable means ~all power-users will be happy, but IME most non-power-users won't work out how to change it even if it bothers them. 

How do you feel about changing the default style? I think either "%message\n[%source%code]" or "%message" would be a clearer default, with more info available to those who want it.

**Comment by fannheyward** [comment]
I don't like to change default style. Current style `[source code] [E] message` in most case is ok, for example:

1. `[pylint E0104] [E] Return outside function`
2. `[json 515] [E] Colon expected`
3. `[tsserver 6133] [I] 'a' is declared but its value is never read.`

The code part is needed and useful for users. On clangd side, the noisy is because _too-long-error-code_. We can overwrite the default `diagnostic.format` in `coc-clangd`, I make it default `%message [%source]`.

**Comment by chemzqm** [comment]
@fannheyward overwrite default configuration by extension doesn't seem to be a good idea, the user install an extension and the behavior unexpected changed.

**Comment by fannheyward** [comment]
@chemzqm the overwrite configurations has been removed.
