### ISSUE TITLE
switchSourceHeader in split

### ISSUE THREAD

**Issue by hnspn** [clangd/coc-clangd#70]
Add the option to open the other file in a split.
Not sure if it's possible to pass args to CoC commands.
something like this would be nice.

```
:CocCommand clangd.switchSourceHeader v
:CocCommand clangd.switchSourceHeader s
```

not sure how useful it is since you can just do this
`nmap <silent> <M-O> :vs <CR> <BAR> :CocCommand clangd.switchSourceHeader<CR>`

**Comment by fannheyward** [comment]
Set `"coc.preferences.jumpCommand": "split` to your coc-settings.json. Search `coc.preferences.jumpCommand` in `:h coc-nvim.txt@en`.
