### ISSUE TITLE
China cannot reach the url of "https://registry.npmjs.org/"

### ISSUE THREAD

**Issue by AFUL1991** [clangd/coc-clangd#700]
Note: we mostly implement features in the clangd language server, and rely on coc.nvim's LSP client framework to expose these in vim. Features requiring a lot of coc-specific work are unlikely to be implemented.

I'm from China, but I cannot use the command of `:CocInstall coc-clangd` to install coc-clangd. Because of the GFW, we cannot reach "https://registry.npmjs.org/", and I don't know how to change the source to the mirror source in China.

**Comment by fannheyward** [comment]
You can setup proxy, check `:h coc-config-http`, or change npm register, check `:h coc-config-npm`.

**Comment by AFUL1991** [comment]
thank you! i don't know how to use the command 'coc-config-npm'，could you give me an example?



---Original---
From: "Heyward ***@***.***&gt;
Date: Thu, Nov 7, 2024 01:04 AM
To: ***@***.***&gt;;
Cc: "Wenjuan ***@***.******@***.***&gt;;
Subject: Re: [clangd/coc-clangd] China cannot reach the url of"https://registry.npmjs.org/" (Issue #700)




 
You can setup proxy, check :h coc-config-http, or change npm register, check :h coc-config-npm.

**Comment by fannheyward** [comment]
`:h coc-config-npm`.

**Comment by AFUL1991** [comment]
> `:h coc-config-npm`. 

OK，thank you！
