### ISSUE TITLE
clangd.compilationDatabasePath breaks the default behavior

### ISSUE THREAD

**Issue by richardtsai** [clangd/coc-clangd#72]
5e3c4523164860bc177cc548753abee7b9e8cdef introduces an option `clangd.compilationDatabasePath`, which will be always sent to clangd as an initialization option. But if this is not set (which is the most common case), `''` will be sent to clangd and breaks the default behavior which searches the ancestor directories.

**System information**
Clangd version (from the log, or `clangd --version`): 2cf52504bb076d24c23f161e92340828052b69f7
clangd extension version (from `:CocInfo`): 6db291b6eb42dfb5d5755223f7ccdeeb06b2575c
Operating system: Linux

**Comment by fannheyward** [comment]
Please try v0.4.13.
