### ISSUE TITLE
SDL pp_file_not_found

### ISSUE THREAD

**Issue by Clingonboy** [clangd/coc-clangd#74]
I have a problem with  SDL library
the program is compile correctly but I have an error in vim, coc-clangd do not see the library:

the error is pp_file_not_found

`                                                              
     vim version: NVIM v0.4.3                                                        
     node version: v10.19.0                                                          
     coc.nvim version: 0.0.78-0ff42027ff                                             
     coc.nvim directory: /home/uge/.config/nvim/plugged/coc.nvim                     
     term: xterm-256color                                                            
     platform: linux                                                                 
                                                                                     
     Output channel: clangd log                                                   
                                                                                    
    I[17:56:25.846] clangd version 9.0.1-12                                         
    I[17:56:25.846] Working directory: /home/uge/Sandbox/cprog                      
    I[17:56:25.846] argv[0]: /usr/bin/clangd                                        
    I[17:56:25.846] Starting LSP over stdin/stdout                                  
    I[17:56:25.848] <-- initialize(0)                                               
    I[17:56:25.849] --> reply:initialize(0) 0 ms                                    
    I[17:56:25.860] <-- initialized                                                 
    I[17:56:25.860] unhandled notification initialized                              
    I[17:56:25.863] <-- textDocument/didOpen                                        
    I[17:56:25.864] Failed to find compilation database for /home/uge/Sandbox/cprog/demo.c
    I[17:56:25.864] --> textDocument/clangd.fileStatus                              
    I[17:56:25.864] Updating file /home/uge/Sandbox/cprog/demo.c with command clangd fallback
    [/home/uge/Sandbox/cprog]  `
`

**Comment by kadircet** [comment]
Looks like you don't have a compile_flags.txt or compilation_database.json set up. That file tells clangd where to find include files, you can check [project setup guide](http://clangd.llvm.org/installation.html#project-setup) for details.

If you set everything correctly, `clangd fallback` in `Updating file /home/uge/Sandbox/cprog/demo.c with command clangd fallback` should disappear.

**Comment by Clingonboy** [comment]
I solve my problem, was my error.
To solve I used building system meson that generate compile_commands.json file and in this way coc-clang recognized the library.
Thanks

**Comment by h-khoza** [comment]
> I solve my problem, was my error.
> To solve I used building system meson that generate compile_commands.json file and in this way coc-clang recognized the library.
> Thanks

cab you please Help me, step by step how on how you solved it, I am using coc-clang and opencv in neovim v5

**Comment by MichaelOren** [comment]
I am having the same error with the MPI library on mac, could you post the example compile_commands.json so that I can use it as a template.
Thanks!!

**Comment by fgr1986** [comment]
@MichaelOren you can install `bear` and run `bear make` to generate it automatically
