### ISSUE TITLE
Would coc-clangd find compilation database under current directory or parent path ?

### ISSUE THREAD

**Issue by HolaYang** [clangd/coc-clangd#77]
Unless I specify `clangd.compilationDatabasePath` option in coc-settings of my local repostory, coc-clangd cloud not find `compile_commands.json` correctly ?

In fact, `compile_commands.json` exist in parent directory of current directory, such as 
```
- dir1
  - compile_commands.json
  - workspace
    - src
```

**Comment by HolaYang** [comment]
Sorry to tag `bug` on this issue.

**Comment by fannheyward** [comment]
clangd will find `compile_commands.json` in your project root.

**Comment by HolaYang** [comment]
For some specific build system, `compile_commands.json` exist in *root* of the whole project, but there is only one sub-directory I care about. So, usually, I would like enter this sub-directory and open vim there to reduce file-indexing costing for my file indexing engine plugin like leaderf.

**Comment by fannheyward** [comment]
Try `clangd.fallbackFlags`

**Comment by fannheyward** [comment]
Can you share me some docs of `--compile-commands-dir`?

**Comment by HolaYang** [comment]
> clangd version 10.0.0
> clangd compilation flags options:
>  --compile-commands-dir=<string> - Specify a path to look for compile_commands.json. If path is invalid, clangd will look in the current directory and parent paths of each source file

**Comment by HolaYang** [comment]
How could I use any variables like `pwd` to specify **parent directory** of vim runtime path?

**Comment by fannheyward** [comment]
You can set `--compile-commands-dir` in `clangd.arguments`.

**Comment by AlefCS** [comment]
> How could I use any variables or directives like `pwd` to indicate current directory?

I also want to know if there is any way to do this. Tried to use `$(pwd)` and `${PWD}` but without success. I work on a project where the build folder stays in a totally different path outside the project folder but the path is based on the project folder name. In VSCode I can just use the variables provided like `${workspaceFolder}` or `${workspaceFolderBasename}`.

**Comment by ObiWahn** [comment]
At some point I have added/proposed the feature and it made the way init coc-clangd

```
 24     "clangd.enabled": true,
 25     "clangd.compilationDatabaseCandidates": ["${workspaceFolder}-build/current", "${workspaceFolder}-build" ,"${workspaceFolder}/build", "${workspaceFolder}/build_dir" ],
 ```
 
 This works pretty good for all of my projects.

**Comment by fannheyward** [comment]
> this is only for vscode right?

Works for coc.nvim+coc-clangd too.
