### ISSUE TITLE
How to specify the `--compile-commands-dir` option?

### ISSUE THREAD

**Issue by adam900710** [clangd/coc-clangd#79]
Sorry for a newbie question, since just converted from vim-lsp, and not really familiar with json at all.

Although the `README.md` specify the option `clangd.compilationDatabasePath` for the json config file, but the following config is just causing more problem than it solved:
```
"languageserver":{
        "clangd":{
                "compilationDatabasePath":"~/compile_commands.d/kernel/"
        }
}
```

I guess that's not the way how to pass the options for coc-clangd?

**Comment by fannheyward** [comment]
1. `:CocInstall coc-clangd`
2. set `"clangd.compilationDatabasePath":""` in your coc-settings.json

**Comment by adam900710** [comment]
>     2. set `"clangd.compilationDatabasePath":""` in your coc-settings.json

No need to put it under any section?
