### ISSUE TITLE
Sync with shiftwidth, softtabstop, tabstop

### ISSUE THREAD

**Issue by danielfalbo** [clangd/coc-clangd#80]
Every time I format my cpp file with `<Plug>(coc-format)`, the `shiftwidth`  used is 2 so all the tabs (expanded in space characters in my case) adapt to 2 characters width but if I format my code with `gg=G`, they don't, because the `shiftwidth` variable has not been overwritten by coc

https://github.com/neoclide/coc.nvim/issues/2328

**System information**
Clangd version (from the log, or `clangd --version`): Apple clangd version 12.0.0 (clang-1200.0.31.1)
clangd extension version (from `:CocInfo`): Apple clangd version 12.0.0 (clang-1200.0.31.1)
Operating system: macOS

**Comment by oblitum** [comment]
I don't believe doing that is a good idea, it's too intrusive into editor settings. Calling an external formatter should format your code according to the formatter settings, but simply not go about setting your editor tab settings.

**Comment by oblitum** [comment]
Shouldn't have been labeled as bug either.

**Comment by danielfalbo** [comment]
Thank you and sorry for marking this as bug, other lsp do this. Closing this issue, it's a little detail and may be subjective after all 👍
