### ISSUE TITLE
refactorin wit coc-rename don't work across project

### ISSUE THREAD

**Issue by grimgort** [clangd/coc-clangd#84]
refactorin wit coc-rename don't work across project (symbol is used outside main file).

**Comment by kadircet** [comment]
Please provide clangd logs, preferably by passing `-log=verbose` to clangd. See http://clangd.llvm.org/troubleshooting.html#gathering-logs for details.

**Comment by grimgort** [comment]
i have set :   "clangd.arguments": ["-log=verbose"], il my coc config but i don't know where is the log file

**Comment by hokein** [comment]
cross-file rename is enabled by default in clangd 11. From the error message (`symbol is used outside main file`), I believe you are using  clangd10 (you try it with command-line flag `cross-file-rename=true`, you may hit bugs as this feature is experimental in clangd10).

**Comment by grimgort** [comment]
thank you. that s work. 
But  command  clangd.install don't work behind proxy with   "http.proxy" correctly configured in coc-setting.json (test with coc-marketplace).
