### ISSUE TITLE
Don't show the same candidate word

### ISSUE THREAD

**Issue by kdurant** [clangd/coc-clangd#85]
![QQ截图20200924103225](https://user-images.githubusercontent.com/2704364/94094216-85ded200-fe51-11ea-82ca-e2dd2625040b.png)

**Comment by kadircet** [comment]
Please provide clangd logs, preferably by passing `-log=verbose` to clangd. See http://clangd.llvm.org/troubleshooting.html#gathering-logs for details. 

They are most likely different symbols that somehow end up having the same label and it is impossible to figure out what went wrong just by looking at the screenshot.
