### ISSUE TITLE
Clangd does not recognize basic headers (cpp file)

### ISSUE THREAD

**Issue by Chaoticsys101** [clangd/coc-clangd#88]
coc-clangd doesn't recognize basic headers (I only use it for C++, don't know about C), such as string and iostream.

![Capturar](https://user-images.githubusercontent.com/67800528/95978826-a1b31380-0e12-11eb-87b4-0127a4dfbfb8.PNG)

**System information**
Clangd version (from the log, or `clangd --version`): 10.0.0
Operating system: Windows 10

**Comment by fannheyward** [comment]
Setup `compile_commands.json` for your project, https://clangd.llvm.org/installation.html#project-setup.
