### ISSUE TITLE
How can I enable clangd index?

### ISSUE THREAD

**Issue by fcying** [clangd/coc-clangd#91]
**System information**
Clangd version (clangd version 10.0.0 (https://github.com/llvm/llvm-project d32170dbd5b0d54436537b6b75beaf44324e0c28)):
clangd extension version (from `:CocInfo`):
```
## versions
vim version: NVIM v0.4.4
node version: v14.13.1
coc.nvim version: 0.0.79-80ae19dee6
coc.nvim directory: ~/.vim/.plugged/coc.nvim
term: xterm-256color
platform: linux
```
Operating system: debian10

When I use `coc-clangd`, it works fine, but there is not `.clangd` index directory generated in the directory. 
I try set ycm's clang argument `clangd --background-index=true -header-insertion-decorators=0 -resource-dir=~/clang/lib/clang/10.0.0 -limit-results=500`(use ycm clang can gen index dir) to `clangd.arguments`, but still no directory generated.
How can I enable clangd index?

**Comment by fannheyward** [comment]
Try  `"clangd.arguments": ["--background-index"]`

**Comment by fcying** [comment]
I had try 
```
"clangd.arguments": ["--background-index"]
"clangd.arguments": ["--background-index=true"]
```
but still no directory generated.

**Comment by kadircet** [comment]
You need to have a compile_commands.json to tell clangd about your project files. otherwise it cannot index your project.

**Comment by fcying** [comment]
@kadircet can't use `compile_flags.txt` ?  when I use ycm, I also use `.ycm_extra_conf.py`, not use `compile_commands.json`

**Comment by fannheyward** [comment]
> Be aware that using compile_flags.txt means background indexing won't work, as it doesn't provide the list of files to consider part of the project.

https://github.com/clangd/coc-clangd/issues/28#issuecomment-612569340

**Comment by fcying** [comment]
@fannheyward @kadircet Got it. Thanks.
