### ISSUE TITLE
printf snippet is strange

### ISSUE THREAD

**Issue by GopherJ** [clangd/coc-clangd#92]
Sorry I'm not sure if it's a coc-clangd issue yet

here is how it looks like while typing `printf`:

![image](https://user-images.githubusercontent.com/33961674/96365449-ec010100-1140-11eb-8e37-155f6e937cf5.png)

and hit enter:

![image](https://user-images.githubusercontent.com/33961674/96365456-f91df000-1140-11eb-936a-0c51cb598ac9.png)

**Comment by GopherJ** [comment]
is it a coc-snippet issue?

**Comment by fannheyward** [comment]
The snippet you selected is not from clangd.
