### ISSUE TITLE
Go to definition / references bugs

### ISSUE THREAD

**Issue by yueyingjuesha** [clangd/coc-clangd#93]
EXAMPLE:
```c++
class A {
  virtual void test() = 0;
}

class B : public A {
 test() {.....}
}
shared_ptr<A> obj = make_shared<B>();
obj->test()
```
I noticed that when I call gotodefinition at obj->test(), code jump to class A virtual function, not class B implementation
Every time I have to manually search who inherits A and navigate to the correct place.

And go to references even worse, the returned location list is sometimes incomplete, which makes me hard to rely on this functionality.

I understand that it's quite hard to jump to correct place when polymorphism involved. So I am wondering is there a way that let the user manually edit and save the locations returned by gotodef, gotoref? At leasest, I am able to only search once and save the correction jumping results instead of doing multiple rounds of repeated workflows, which literally drive me insane.

**Comment by sam-mccall** [comment]
A::test() is a useful result for go-to-def - it is certainly accurate and is the source of truth for documentation, default parameters etc.

It's unlikely we'll ever do the dataflow analysis required to establish that B::test() is the method being called (as opposed to a possible alternative subclass C::test()).

Nevertheless surfacing all known overrides of A::test() is useful. The most obvious place for this is the `textDocument/implementation` call which we don't implement yet (this is https://github.com/clangd/clangd/issues/29). Another possible place is go-to-definition on the *declaration* of the virtual method. (e.g. `obj->test()` would go to `virtual void test()` in A, but `virtual void test()` would go to B::test.

**Comment by yueyingjuesha** [comment]
> A::test() is a useful result for go-to-def - it is certainly accurate and is the source of truth for documentation, default parameters etc.
> 
> It's unlikely we'll ever do the dataflow analysis required to establish that B::test() is the method being called (as opposed to a possible alternative subclass C::test()).
> 
> Nevertheless surfacing all known overrides of A::test() is useful. The most obvious place for this is the `textDocument/implementation` call which we don't implement yet (this is [clangd/clangd#29](https://github.com/clangd/clangd/issues/29)). Another possible place is go-to-definition on the _declaration_ of the virtual method. (e.g. `obj->test()` would go to `virtual void test()` in A, but `virtual void test()` would go to B::test.

but it seems to me that when I call go-to-definnition on the declaration `virtual void test()`, the command doesn't do anything, just stand there

**Comment by fannheyward** [comment]
clangd's issue, not coc-clangd.

**Comment by sam-mccall** [comment]
(BTW textDocument/implementation is implemented in the upcoming clangd 12 release. go-to-definition and find-references have some support for inheritance too.)
