### ISSUE TITLE
Disable file status

### ISSUE THREAD

**Issue by swarn** [clangd/coc-clangd#95]
I haven't found a way to disable file status. I'd like to remove the `clangd: idle` from my status line; I can always check it with `:echo g:coc_status`.

I use airline, so there's `let g:airline#extensions#coc#enabled = 0`, but that also disables the warning/error status.

**Comment by swarn** [comment]
Oops, I see now that this issue is out of scope for `coc-clangd`. For others who are curious, `:help coc-status-manual`

**Comment by Rahlir** [comment]
I would actually vote to re-open this. Yes, it is possible to use the configs outlined in `coc-status-manual` to only show diagnostic info in status line, but it would also make sense to leave `coc#status` in the status line and have `clangd` filestatus silenced. In my experience `coc-clangd` is by far the most chatty LSP. For me it makes the statusbar flicker everytime I type something. This is really inconvenient and forces me to remove `coc#status` from status line whenever I work with c/c++. It seems quite strange that this is not an optional feature.

**Comment by fannheyward** [comment]
@Rahlir fixed in https://github.com/clangd/coc-clangd/issues/524, you can disable it with `clangd.disableFileStatus`.
